### ISSUE TITLE
Readme Instructions Don't Work On Windows

### ISSUE THREAD

**Issue by mike-thompson-day8** [rethinkdb/horizon#142]
Attempting to follow the README's instructions on Windows 10 ...  

These two steps work okay: 
```
$ npm install -g horizon
$ hz init my-app
```
(Note I used `my-app`, rather than `myapp` as per the README, but that shouldn't make a difference, right?) 

This next step does not work (I can see Node blink briefly into existence on "Process Explorer" before disappearing)
```
$ hz serve my-app --dev
```

Here's what I see (which is encouraging but, sadly, not yet accurate):
```
D:\experiments>hz serve my-app --dev
warn: Creating insecure HTTP server.
info: Serving static files from dist
info: Listening on 127.0.0.1:8181.
```

**Comment by dalanmiller** [comment]
Hey @mike-thompson-day8 would you mind trying this out again? I'm going to close the issue for now as we've seen this closed in most instances, but please re-open if it's still occurring for you.
