### ISSUE TITLE
Considering using node-lws a Node.js wrapper for libwebsockets? 

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/horizon#192]
https://github.com/alexhultman/node-lws

> node-lws (or simply lws) is a [libwebsockets](https://libwebsockets.org/index.html) wrapper for Node.js and C++. It exposes an easy to use interface much like the one available in ws. In contrast to ws, node-lws is very lightweight and scales to millions of connections where ws simply chokes due to excessive memory usage.

> node-lws uses less than 40% the memory per connection compared to ws.
> node-lws establishes connections in less than 10% the time compared to ws.
> node-lws echoes messages in less than 30% the time compared to ws.

> Primus support is included in 5.0. Use 'lws' as transformer & report any issues here.

**Comment by ghost** [comment]
You shouldn't use lws, I will unpublish it very soon as it has been deprecated for some months now. You should look into uws instead if you are still interested in performant websockets.

**Comment by deontologician** [comment]
Closing since there's another issue for uws: #698
