### ISSUE TITLE
find( ... ).fetch() shouldn't require forEach

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/horizon#200]
It seems a bit heavy to have to setup forEach handlers just to get a single document. Would it be bad just to return this document or be able to pass the callback to `.fetch()`? Since `.forEach` follows `.fetch()` every time anyway, is there a reason to have both? 

This: 
```js
// Retrieve an single item by id
const retrieveMessage = (id) => {
  chat.find(id).fetch()
    .forEach(
    // Retrieval successful
    (result) => { chats.push(result);},
    // Error occurred
    (error) => console.log(error))
}
```
Or: 

```js
// Retrieve an single item by id
const retrieveMessage = (id) => {
  chat.find(id).fetch(
    // Retrieval successful
    (result) => { chats.push(result);},
    // Error occurred
    (error) => { console.log(error); })
}
```

**Comment by deontologician** [comment]
I'm not sure this issue makes sense without a concrete proposal. I'm going to close it for now
