### ISSUE TITLE
For existing applications wanting to use Horizon, need to enable CORS 

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/horizon#239]
If I already have an application / application environment all set up and want to use Horizon, my option will be to load my app from my normal static file server - `localhost:5000/index.html` - but make connections to Horizon - `localhost:8181`. This will violate the [same-origin policy](https://en.wikipedia.org/wiki/Same-origin_policy#Relaxing_the_same-origin_policy) and [cause](https://www.google.com/search?q=webpack+cors&oq=webpack+cors&aqs=chrome..69i57j0j69i60j0l2j69i60.1112j0j7&sourceid=chrome&ie=UTF-8) [headaches](https://www.google.com/search?q=flask+cors&oq=flask+cors&aqs=chrome..69i57l2j69i60l4.707j0j7&sourceid=chrome&ie=UTF-8).

We should add another flag (`--cors "*"`?) to come default with `--dev` mode which will enable the CORS headers on any paths under the `/horizon` paths and the websocket endpoint.

**Comment by natew** [comment]
Was this not released with 1.0?

**Comment by dalanmiller** [comment]
Unfortunately no @natew, are you coming across an issue where you need CORS?

**Comment by natew** [comment]
We are doing a little nginx proxy in front so no worries.

**Comment by dalanmiller** [comment]
Hey if you think it novel, would you mind sharing the nginx config? Are you
just adding headers to the responses with Nginx? @natew 

2016-05-24 16:01 GMT-07:00 Nate Wienert notifications@github.com:

**Comment by deontologician** [comment]
@dalanmiller was this fixed in #565 where the `access_control_allow_origin` flag was added?

**Comment by dalanmiller** [comment]
Yup, as a baseline this looks good 👍
