### ISSUE TITLE
Integrating Parse Dashboard?

### ISSUE THREAD

**Issue by kulshekhar** [rethinkdb/horizon#253]
RethinkDB has a fantastic web interface for administering it. However, given that Horizon is aimed at developers who want to minimize backend related tasks, would it make sense to try and integrate [Parse dashboard](https://github.com/ParsePlatform/parse-dashboard) in?

Since Parse dashboard works with Parse server, I imagine that it gets most of its data using REST (or REST like) calls to Parse server. Based on an initial (and limited understanding) it seems to me that any back-end that exposes the data and metadata required by Parse dashboard could be integrated with it.

If my understanding is right, this would mean that just by implementing and exposing the required endpoints (hopefully without any architectural changes), Horizon could make use of a tool that is understood and used by a lot of users that Horizon is being built for. 

The familiarity of the dashboard alone might make Horizon attractive to a lot of existing Parse users. If you consider all the goodness that RethinkDB offers over MongoDB, it would become almost a no brainer, at least for new projects.

**Comment by deontologician** [comment]
Closing in favor of #154
