### ISSUE TITLE
'npm install -g horizon' is broken for some versions of npm

### ISSUE THREAD

**Issue by kerbelp** [rethinkdb/horizon#254]
Hi, 
Before diving into the code, I noticed that the installation is broken.
npm ERR! 404 'horizon/server' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'horizon'

**Comment by Cinderhaze** [comment]
As an FYI, I freshly installed npm on my Ubuntu 15.10 machine ( which installed npm 1.4.21) and ran into this exact same problem trying to run npm install -g horizion.

**Comment by ghost** [comment]
Hi all,

I have just had this exact same issue on Windows 7 64bit.

Node v5.10.1 & npm v1.4.9

**Comment by deontologician** [comment]
@jakkblakk Would you mind opening a new issue with the problems you've encountered? Our windows support is more theoretical than actual at the moment, so it may be unrelated to this issue

**Comment by dalanmiller** [comment]
@jakkblakk @Cinderhaze Not sure if `npm` has the same versioning on Windows as it does non-Windows but I think you need at least `npm 3.0.0` for the correct package namespacing `@horizon/[client|server]`.

**Comment by Cinderhaze** [comment]
I was putting my info out there as a point of reference.  Not being
familiar with node/npm, having heard about horizon and wanting to give it a
try, I was surprised when the getting started instructions didn't work.
I'm not sure if you want to tie in some sort of getting started/FAQ to the
setup instructions that would point people down the right path to having a
new enough node installed.

I did what I thought the instructions told me to do, and it didn't work.  I
know you don't control node/npm versions of packages in package managers
for all distros, but a quick little pointer on the getting started page may
go a long way for people who want to get up and running.

On Mon, May 23, 2016 at 6:53 PM, Daniel Alan Miller <
notifications@github.com> wrote:

> @jakkblakk https://github.com/jakkblakk @Cinderhaze
> https://github.com/Cinderhaze Not sure if npm has the same versioning
> on Windows as it does non-Windows but I think you need at least npm 3.0.0
> for the correct package namespacing @horizon/[client|server].
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/rethinkdb/horizon/issues/254#issuecomment-221119596

## 

 ~ Daryl Wiest

**Comment by dalanmiller** [comment]
Hey again @Cinderhaze, apologies that it's not working out. I think if you try upgrading your `npm` though things should be fine. Also any error messages you got would help.

AFAIK there's no way currently for us to block the ability to install `horizon` on outdated versions of `npm` or else we would do so and provide you with a much more helpful message.

**Comment by marshall007** [comment]
@dalanmiller actually, in the `package.json` you can specify the [`engines`](https://docs.npmjs.com/files/package.json#engines) field:

``` js
{
  "name": "@horizon/server",
  // ...
  "engines" : {
    "node" : "<semver>",
    "npm" : "<semver>"
  }
}
```

**Comment by dalanmiller** [comment]
Thanks @marshall007, I'm going to add this.
