### ISSUE TITLE
Issues getting Horizon working with React Native

### ISSUE THREAD

**Issue by dferber90** [rethinkdb/horizon#255]
I took horizon for a spin with a react-native project.

I have set up an example project you can use to experiment with it yourselves at [dferber90/horizon-react-native](https://github.com/dferber90/horizon-react-native).
### Current issues

Currently there is at least one issue in [here](https://github.com/rethinkdb/horizon/blob/b5d42cc3b7908fc5bd544725c1ee26d5bb10c665/client/src/auth.js#L71), because `window.location` is undefined in React Native.
After `npm install`ing, it's possible to manually fix this by editing `horizon-react-native/HorizonExampleApp/node_modules/@horizon/client/lib/auth.js` and changing line 98

``` diff
- var parsed = queryParse(window.location.search);
+ var parsed = queryParse(window && window.location && window.location.search);
```

After doing this, press `CMD+R` in the simulator. Now an alert should appear saying the Horizon client is connected... which means it works :)
### Authentication

I haven't fully understood how horizon does authentication yet, so I can describe the problems I discovered only vaguely.
#### Tokens

When using tokens, the token would have to be stored on the device using [AsyncStorage](https://facebook.github.io/react-native/docs/asyncstorage.html#content) instead of `localStorage`. Having low-level functions which allow developers to pass the current token to Horizon from any source and specify how to save any new tokens would be helpful here.
#### OAuth

The current flow of using OAuth is probably not possible with React Native since the OAuth token can't be read form the callback URL, but maybe from the URI Scheme. I've never created OAuth integration for a native device before, so I can't really tell.

**Comment by ndarilek** [comment]
So are these resolved, and should Horizon be working with React Native? I went through the various Horizon issues to get a sense of where it was, and this led me to believe that it still wasn't working. Then I watched the video at https://www.youtube.com/watch?v=xRK0SYSgVF0&feature=youtu.be and it does seem that it works. Am I missing something?

Thanks.

**Comment by deontologician** [comment]
From what I can tell, the only remaining issue with React Native is that we don't interact with AsyncStorage instead of LocalStorage. The big impediment being that the interface is different (AsyncStorage is async). In addition, we'd need to figure out how best to do OAuth redirects in React Native, since there's not actually a browser or a window.location

**Comment by dferber90** [comment]
When the app is closed or moved to the background the Websocket connection should be terminated, and reopened when the app is activated again. On React Native's side [AppState](https://facebook.github.io/react-native/docs/appstate.html) can be used for this.

When the phone loses internet connectivity you'd have to handle that as well. [NetInfo](https://facebook.github.io/react-native/docs/netinfo.html) can be used for this. Specifically, you'd want to handle the case when it gains connection again to reconnect Horizon.

Both of these are concerns of the React Native developer, not Horizon itself as long as API is there to support reconnecting - and it seems there is 👍 

Since these steps are pretty much the same for every React Native app, maybe we could extract them into an npm package.

**Comment by deontologician** [comment]
That seems reasonable. I think we should get good reconnection working pretty soon it seems like.
Also, see #429 for how we might get around needing to abstract away AsyncStorage (at least for horizon's purposes)

**Comment by lirbank** [comment]
The horizon client seems to work with react-native 0.31.0 (android+ios) and the the latest `next` branch of horizon, as long as I remove the babel config (as pointed out here https://github.com/rethinkdb/horizon/pull/750).

**Comment by deontologician** [comment]
That's good, I can probably move the babel config back out to a separate file. I forget exactly why I moved it in

**Comment by lirbank** [comment]
Ok, great! 

Oh, there is one more things that needs to be tweaked for it to work. Working on a fix. BRB.

**Comment by lirbank** [comment]
WRT the babel config, if you remove it then `./setupDev.sh` will not work anymore (eg `SyntaxError: Unexpected token import`). 

It is still possible to build the client without the babel conf, with `npm install`.

EDIT: Or, `./setupDev.sh` actually works but the `hz` cli it produces will not.

**Comment by lirbank** [comment]
Ok, got it working. Assuming you have one project for your horizon app (horizonApp) and one for you react native app (reactNativeApp), the steps as of horizon 2.0.0-beta-7 are as follows:
1. For android to work, apply this patch https://github.com/rethinkdb/horizon/pull/770/files
2. Clone horizon `git clone https://github.com/rethinkdb/horizon.git`
3. Disable the babel preset in `horizon/client/package.json`, ex https://github.com/lirbank/horizon/commit/8b62b2d115efcfab185d69ef2fde5c8672537d76
4. Install your local horizon client in your react native app:

```
$ cd reactNativeApp
$ npm install ../horizon/client/ --save
```
1. When you install the client above, you also break the cli (it needs the babel preset), so fix let's fix that. First re-enable the babel preset in `horizon/client/package.json` (eg. reverse step 3 above), then rebuild the client:

```
$ cd ../horizon/client/
$ npm install
```
1. Start the horizon server (must be the latest server too, or else RN won't connect to it):

```
$ cd ../horizonApp/
$ node ../horizon/cli/src/main.js serve --dev --debug
```

Seems like a lot of steps, but it all boils down to that the Horizon cli must be built with the babel preset enabled while the Horizon client must be built without the babel preset for it to work in React Native.

**Comment by smkhalsa** [comment]
Thanks @lirbank for the workaround. Unfortunately, I'm getting this error when I try `npm install ../horizon/client/ --save`.

> @horizon/client@2.0.0 prepublish /Users/smkhalsa/code/horizon/client
> npm run compile && npm run build
> 
> @horizon/client@2.0.0 compile /Users/smkhalsa/code/horizon/client
> node ./scripts/compile.js

module.js:457
    throw err;
    ^

Error: Cannot find module 'shelljs/global'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/smkhalsa/code/horizon/client/scripts/compile.js:1:63)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by smkhalsa** [comment]
I just tried it again, and it looks like it worked. I believe the only thing that changed was I reinstalled horizon globally.

**Comment by smkhalsa** [comment]
@deontologician can we implement this change so react-native can work out of the box?

**Comment by deontologician** [comment]
Yes, we are going to, and I want to get a proper test setup for react
native so we dont accidentally break it again

**Comment by deontologician** [comment]
Just an update, this isn't dead. I'm trying very hard to get react native up and running (endless configuration troubles). I now understand why you react native people are so persistent, it's a gauntlet getting the default app to work.

_Update_: It works!
![selection_093](https://cloud.githubusercontent.com/assets/1366/18490525/3d7eea5e-79b7-11e6-9b84-2409afb675b0.png)

**Comment by deontologician** [comment]
Ok, a fix is up in #823 if anyone wants to try it out. Be aware that if you do, you need to build the package and install it, you can't just `npm link` it since it will still pick up the babelrc file

**Comment by lirbank** [comment]
Yes, https://github.com/rethinkdb/horizon/pull/823 seems to solve the babel-loose problem!

**Comment by anhtuank7c** [comment]
@smkhalsa How do you pass these error?
I repeat `npm install ../horizon/client/ --save` again and again, still stuck.
I have horizon install global already.
:(
![screen shot 2017-05-04 at 10 19 47 am](https://cloud.githubusercontent.com/assets/3163410/25689539/3ff09b44-30b3-11e7-9ffa-9a1c2726ce02.png)

**Comment by kourindouhime** [comment]
@anhtuank7c 
    cd ../horizon/client
    npm install
    cd yourapp
    npm install path-to-horizon/client --save

**Comment by davidroman0O** [comment]
Hope one day it i'll be fixed and we won't have to make all of this tricky hack! :)
