### ISSUE TITLE
Allow security options in reql_connection.js

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/horizon#288]
Right now only host/port are accepted as options. Ideally we'd accept certificate paths, user/password etc, that 2.3 allows

**Comment by danielmewes** [comment]
I've been informed that Horizon currently doesn't work with non-admin users because it accesses some of the system tables. This will be resolved with RethinkDB 2.4 https://github.com/rethinkdb/rethinkdb/issues/5692 .

**Comment by danielmewes** [comment]
@Tryneus it looks like we're using system tables to a) wait for indexes to become ready and b) to check the RethinkDB server version, right? I wonder if we could implement some kind of fallback so Horizon still works with non-admin users (though possibly not properly waiting for indexes, and not checking the server version) until we ship RethinkDB 2.4.

**Comment by deontologician** [comment]
Fixed by #507
