### ISSUE TITLE
Make Rxjs a peer dependency

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/horizon#306]
This would allow users to bring their own RxJS, instead of locking them to whatever version comes with horizon

**Comment by bopjesvla** [comment]
Is this as simple as moving rxjs to peer dependencies and adding some documentation?

**Comment by deontologician** [comment]
Ok, I am confidently closing this one. My confusion was that the package.json's `peerDependency` had anything at all to do with how webpack decides whether to bundle a module or not. It doesn't, of course.

Making rxjs a peer dependency when it's actually a regular dependency is just a bad idea, since it means an extra manual step when installing on node etc.
