### ISSUE TITLE
Default file for schema.toml in the project directory

### ISSUE THREAD

**Issue by Tryneus** [rethinkdb/horizon#378]
It may be useful for `get-schema` and `set-schema` to default to a specific file in the project directory.  Right now `get-schema` outputs the TOML to stdout, and `set-schema` takes the file as a positional parameter.

This may be complicated in the case where there is no project directory, and the script is just pointed to a rethinkdb instance to connect to.

**Comment by deontologician** [comment]
We have .hz/schema.toml now in 2.0.0
