### ISSUE TITLE
Add shortcutting to requests which do not need validation

### ISSUE THREAD

**Issue by Tryneus** [rethinkdb/horizon#380]
At the moment, all write requests take the 'slow' path, most of which involve two sequential ReQL queries to ensure that versions do not change after validation.  If a request matches a rule that does not have a validator, we can go straight to the write and save some time and effort.

Also, many write requests are still performing the second query even if all rows were rejected by validators.

These changes are not critical, as they do not greatly affect results, but could lower latency in development environments and some permissions configurations.

**Comment by deontologician** [comment]
@Tryneus this is done right?
