### ISSUE TITLE
support for sending/receiving files in the client

### ISSUE THREAD

**Issue by stellanhaglund** [rethinkdb/horizon#388]
It would be really nice to be able to send and receive files using the client.

**Comment by stellanhaglund** [comment]
I havent tried yet but is there anything stoppning me from sending a file to the server using sendRequest?

**Comment by deontologician** [comment]
Nothing at all. You'd need to base64 encode it though since it has to be in json

**Comment by deontologician** [comment]
This is subsumed by #70 and #186
