### ISSUE TITLE
findAll with an array of objects does not work

### ISSUE THREAD

**Issue by flipace** [rethinkdb/horizon#391]
I'm trying to use _findAll_ like this:

`query.findAll([ { name: 'a' }, { name: 'b' } ]);`

This throws an error: 

`error: Error (Error: "find" is required) when handling error (Error: "find" is required)."`

If i use:
`query.findAll.apply(query, [ { name: 'a' }, { name: 'b' } ])`
it works as expected.

**Comment by danielmewes** [comment]
`findAll` is variadic and takes multiple arguments, not a single array (it is different from e.g. `store` in this respect). So you should write:

``` js
query.findAll( { name: 'a' }, { name: 'b' } );
```

**Comment by flipace** [comment]
@danielmewes alright, what is meant with the array syntax in the client readme? 

`findAll( { id: <any> } [, { id: <any> }] )`

My seconds guess based on this was that the first arg should be an object and the second can be an array.

And i honestly think that it should be possible to pass an array here, at least until joins are done (https://github.com/rethinkdb/horizon/issues/308) this would be very helpful.

**Comment by danielmewes** [comment]
@flipace I think it's meant to indicate that you can _optionally_ specify additional arguments. It's a bit clearer in our new documentation I think: http://horizon.io/api/collection/#findall

I believe the document IDs can be arrays in Horizon (right @deontologician?). So if you pass an array, `findAll` is going to assume that you passed a single document ID, and it can't know that you meant to fetch multiple different keys.
The error message is pretty confusing though. We should improve that.

**Comment by deontologician** [comment]
Yeah, thats correct, we allow array ids explicitly, which is why we have to be so careful about variadic vs. array wrapped

**Comment by flipace** [comment]
Okay. maybe something like this would be easier to implement? (that would also greatly reduce the size of the request - could be converted to variadic notation on server side...)

``` Javascript
query.findAll( { name: ['a', 'b'] } );
```

**Comment by danielmewes** [comment]
@flipace I think that wouldn't work either, because name might also contain arrays and it's still not clear if you mean to look for the two values `'a'` and `'b'`, or for a single value `['a', 'b']` (Horizon will assume the latter).
