### ISSUE TITLE
Uncaught SyntaxError: Unexpected token e in JSON at position 0

### ISSUE THREAD

**Issue by vijaysimhajoshi** [rethinkdb/horizon#399]
Trying horizon 1.0.1 version for the first time and hitting the below issue:

I m able to run the hz serve myapp --dev --debug successfully, but i m unable to see the marquee message.

**Chrome browser console error:
Uncaught SyntaxError: Unexpected token e in JSON at position 0**

hz serve command output:

App available at http://127.0.0.1:8181
debug: RethinkDB stdout: Recursively removing directory /Users/vsj/Desktop/horizon_projects/myapp/rethinkdb_data/tmp
debug: RethinkDB stdout: Initializing directory /Users/vsj/Desktop/horizon_projects/myapp/rethinkdb_data
info: RethinkDB Running rethinkdb 2.3.2 (CLANG 7.3.0 (clang-703.0.29))...
info: RethinkDB Running on Darwin 14.5.0 x86_64
debug: RethinkDB stdout: Loading data from directory /Users/vsj/Desktop/horizon_projects/myapp/rethinkdb_data
error: rethinkdb stderr: warn: Cache size does not leave much memory for server and query overhead (available memory: 876 MB).
info: RethinkDB Listening for intracluster connections on port 56111
info: RethinkDB Listening for client driver connections on port 56112
info: RethinkDB Listening for administrative HTTP connections on port 56113
RethinkDB
   ├── Admin interface: http://localhost:56113
   └── Drivers can connect to port 56112
Starting Horizon...
debug: Added HTTP handler at /horizon/horizon.js
debug: Added HTTP handler at /horizon/horizon.js.map
debug: Added HTTP handler at /horizon/auth_methods
info: Connecting to RethinkDB: localhost:56112
info: RethinkDB Listening on cluster addresses: 127.0.0.1, ::1
info: RethinkDB Listening on driver addresses: 127.0.0.1, ::1
info: RethinkDB Listening on http addresses: 127.0.0.1, ::1
debug: RethinkDB stdout: To fully expose RethinkDB on the network, bind to all addresses by running rethinkdb with the `--bind all` command line option.
debug: RethinkDB stdout: Server ready, "VSJ_MacBook_Air_local_9io" 
debug: Connection to RethinkDB established.
debug: running metadata sync
info: Groups metadata synced.
info: Index metadata synced.
info: Collections metadata synced.
debug: adding admin user
debug: redirecting users table
debug: metadata sync complete
info: Metadata synced with database, ready for traffic.
Horizon ready for connections 🌄
debug: Handling HTTP request to horizon subpath: horizon.js
debug: Client connection established.
debug: Handling HTTP request to horizon subpath: horizon.js.map
debug: Client connection terminated.

If you have a question,  please open a new topic in Horizon's Help forum:
    https://discuss.horizon.io/c/get-help

If you're suggesting a feature but aren't sure how it might be implemented, we have a more free-form discussion forum for features:
    https://discuss.horizon.io/c/features

If you're reporting a bug please include the following:
- Server version
- Client version

**Comment by danielmewes** [comment]
I'm not sure if "for the first time" you mean Horizon 1.0.1 or Horizon in general.
If you had used Horizon before, you might have to open the JS console in your browser, run `Horizon.clearAuthTokens()` and then reload the page.

If that doesn't help, we'll need to investigate more.

**Comment by vijaysimhajoshi** [comment]
Horizon.clearAuthTokens() did the trick. I m able to run the app successfully!

Will close the bug. Thanks for the quick response.
