### ISSUE TITLE
Getting started document doesn't give enough structure

### ISSUE THREAD

**Issue by danielcompton** [rethinkdb/horizon#402]
The [getting started](http://horizon.io/docs/getting-started/) document has a lot of good information, but doesn't tie all of the information together into an application. For example:
- In the "putting it all together" section, it doesn't say where the JS file should be saved.
- `renderChats` is mentioned once in the getting started document, but never defined AFAICT.
- There is no updated HTML page to render the chat messages into.

Lots of good stuff there, but not quite enough to get a working application on my part without expending more brain energy to fill in the gaps.

**Comment by danielmewes** [comment]
@danielcompton Similar to RethinkDB, we now have a separate documentation repository for Horizon at https://github.com/rethinkdb/horizon-docs/ . I copied your issue text over to https://github.com/rethinkdb/horizon-docs/issues/49 .
