### ISSUE TITLE
ios/android client

### ISSUE THREAD

**Issue by arden** [rethinkdb/horizon#407]
horizon could support socket.io and ios/android?

**Comment by flipace** [comment]
hey @arden, horizon currently uses engine.io - which is (quote) "the implementation of transport-based cross-browser/cross-device bi-directional communication layer for Socket.IO.".

why would you need socket.io? and what do you mean specifically with ios/android support?

**Comment by arden** [comment]
@flipace Because i'm use socket.io-client-swift https://github.com/socketio/socket.io-client-swift in my ios/android projects already.

**Comment by deontologician** [comment]
Since we already support the engine.io protocol, I'm going to change the name of this topic to Android/Ios client.

**Comment by danielmewes** [comment]
@deontologician Note that this is the same as https://github.com/rethinkdb/horizon/issues/59 then. Should we close one?

**Comment by deontologician** [comment]
Good call. Closing in favor of the older issue.
