### ISSUE TITLE
Database name is invalid

### ISSUE THREAD

**Issue by desenmeng** [rethinkdb/horizon#408]
hz clinet version 1.0.1
node version v6.1.0
rethinkdb version 2.3.2

```
$ hz init example-app && cd example-app && hz serve --dev
```

```
App available at http://127.0.0.1:8181
RethinkDB
   ├── Admin interface: http://localhost:55708
   └── Drivers can connect to port 55707
Starting Horizon...
error: Connection to RethinkDB terminated: ReqlQueryLogicError: Database name `example-app` invalid (Use A-Za-z0-9_ only) in:
r(["example-app", "example-app_internal"])
```

Maybe we can update the [getting-started-docs](http://horizon.io/docs/getting-started/) and transfer the app name in the cli

**Comment by danielmewes** [comment]
Thanks for reporting @demohi .

This was previously mentioned in https://github.com/rethinkdb/horizon/issues/376, and for now the example was changed via https://github.com/rethinkdb/horizon-docs/pull/48 . We'll push the change to our web server soon.

Going to close as a duplicate.

**Comment by desenmeng** [comment]
👍
