### ISSUE TITLE
Global install of horizon has giant test database files

### ISSUE THREAD

**Issue by josephg** [rethinkdb/horizon#411]
Just installed horizon. These giant files are now on my computer:

```
$ du -h /usr/local/lib/node_modules/horizon/node_modules/\@horizon/server/
 74M    /usr/local/lib/node_modules/horizon/node_modules/@horizon/server//rethinkdb_data
 48M    /usr/local/lib/node_modules/horizon/node_modules/@horizon/server//rethinkdb_data_test
```

Not sure if these files are added during post-install or are part of the module, but they shouldn't be there.

```
$ grep version /usr/local/lib/node_modules/horizon/package.json 
  "version": "1.0.1"
```

**Comment by danielmewes** [comment]
Thanks for bringing this to our attention @josephg. Those files indeed shouldn't be there. We must have accidentally packaged them into the NPM.

Pinging @dalanmiller .

**Comment by dv336699** [comment]
@jsehpg out of curiosity, do you always inspect what you global install?

**Comment by deontologician** [comment]
I am really glad he did, dang!

**Comment by josephg** [comment]
@diego-vieira only recently after I noticed another package I was using pulled in 250 megs of dependancies via npm. "I wonder how big horizon is? Whoa how is this 150 megs? ... Oh, look at that"

**Comment by dalanmiller** [comment]
I'm late to this party but I take full blame for this @josephg as I was the perpetrator here, I apologize profusely to your hard drive 😭 . 

Closing this as we have proper `.gitignore` rules now.

**Comment by josephg** [comment]
^_^ bugs will come and go. But seeing everyone rally to get all these issues fixed makes me really happy. Thanks for the great work!
