### ISSUE TITLE
'rethinkdb' not available on windows path

### ISSUE THREAD

**Issue by duncanhunter** [rethinkdb/horizon#412]
Unable to follow getting started with following error

```
C:\code\horizon\example_app
λ hz serve --dev
App available at http://127.0.0.1:8181
serve failed with Error: `rethinkdb` not found in $PATH, please install RethinkDB.
```

I see no instructions for adding or using rethink by command line for windows??

I think it would be a good idea to add instructions for this.

If you're reporting a bug please include the following:
- Server version 2.3
- Client version 1.01

**Comment by danielmewes** [comment]
The best option is probably putting `rethinkdb.exe` into a special folder (let's say `C:\Program Files\RethinkDB`), and then modifying the PATH variable to include that folder.
"My Computer" > "Properties" > "Advanced" > "Environment Variables" > "Path"

**Comment by AlexGehl** [comment]
Thanks worked for me.

**Comment by philj0st** [comment]
the same thing happens for me on linux.
there are no instructions explicitly saying i have to install rethinkdb .. i'm not sure now if it comes as a npm dependency or if i have to install it myself. this should be made clear in the getting started

**Comment by deontologician** [comment]
@phipix01 The installation instructions mention this at the top: http://horizon.io/install/

**Comment by philj0st** [comment]
hhhmm embarassing :blush: i guess i skimmed through a little too fast .. thanks @deontologician
