### ISSUE TITLE
Problem installing new permissions

### ISSUE THREAD

**Issue by houshuang** [rethinkdb/horizon#415]
Horizon 1.0.1, running `hz set-schema` with the following file contents:

```
[groups.default.rules.read]
template = "collection(any()).anyRead()"

[groups.default.rules.write]
template = "collection(any()).anyWrite()"
```

and then `get-schema`, results in:

```
# This is a TOML document

[collections.b]

[collections.groups]

[groups.default]
[groups.default.rules.read]
template = "collection(any()).anyRead()"
[groups.default.rules.write]
template = "collection(any()).anyWrite()"
```

Where do collections.b and collections.groups come from? 

Then, when I try to do run set-schema again on exactly the same file (as part of an automatic setup script for new installs), I get the error message:

```
set-schema failed with Error: Run with "--force" to continue.
These collections would be removed along with their data:
b, groups
    at /Users/stian/src/wallcology/ckx/ckx/node_modules/horizon/src/set-schema.js:187:19
    at tryCatcher (/Users/stian/src/wallcology/ckx/ckx/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/stian/src/wallcology/ckx/ckx/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/stian/src/wallcology/ckx/ckx/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/stian/src/wallcology/ckx/ckx/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/stian/src/wallcology/ckx/ckx/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/stian/src/wallcology/ckx/ckx/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/stian/src/wallcology/ckx/ckx/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

But I never asked for these groups to be created in the first place, so why do they exist, and why should they be removed, given my two lines which just try to open all access to read and write?

**Comment by danielmewes** [comment]
@houshuang Are you running `hz serve` in development mode (with `--dev`), or with the `--auto-create-collection` flag? In that case collections will be automatically created once you run any query that uses them. I suspect that that's where those two collections are coming from. If you don't need them, you can use `--force` and they will be deleted.

**Comment by danielmewes** [comment]
By default, `hz set-schema` completely overwrites the existing settings, which include collections, indexes and permissions.
You can also run `hz set-schema --update`, in which case it will only add new elements or update existing ones if their names match, but will not delete any existing collections or rules.

**Comment by houshuang** [comment]
OK, yes I was automatically creating collections, I just didn't understand
how the permissions had anything to do with my collections. Of course I
should have read the command better, "set-schema", and understood what was
going on. Seems like `--update` is what I need. Thanks!

On Wed, May 18, 2016 at 4:14 PM, Daniel Mewes notifications@github.com
wrote:

> By default, hz set-schema completely overwrites the existing settings,
> which include collections, indexes and permissions.
> You can also run hz set-schema --update, in which case it will only add
> new elements or update existing ones if their names match, but will not
> delete any existing collections or rules.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/rethinkdb/horizon/issues/415#issuecomment-220144203

## 

http://reganmian.net/blog -- Random Stuff that Matters

**Comment by houshuang** [comment]
Trying to use `--update` gives me:

```
~/s/w/c/ckx (fix_sync) $ ./node_modules/.bin/hz set-schema .hz/schema.toml
--update
set-schema failed with ReqlDriverCompileError: Argument 1 to get may not be
`undefined`.
    at ReqlDriverCompileError.ReqlError [as constructor]
(/Users/stian/src/wallcology/ckx/ckx/node_modules/rethinkdb/errors.js:23:13)
    at ReqlDriverCompileError.ReqlCompileError [as constructor]
(/Users/stian/src/wallcology/ckx/ckx/node_modules/rethinkdb/errors.js:35:51)
    at new ReqlDriverCompileError
(/Users/stian/src/wallcology/ckx/ckx/node_modules/rethinkdb/errors.js:46:57)
    at Get.<anonymous>
(/Users/stian/src/wallcology/ckx/ckx/node_modules/rethinkdb/ast.js:1428:17)
    at Get.RDBOp [as constructor]
(/Users/stian/src/wallcology/ckx/ckx/node_modules/rethinkdb/ast.js:1432:8)
    at new Get
(/Users/stian/src/wallcology/ckx/ckx/node_modules/rethinkdb/ast.js:1812:38)
    at
/Users/stian/src/wallcology/ckx/ckx/node_modules/rethinkdb/ast.js:1044:43
    at Table.RDBVal.get
(/Users/stian/src/wallcology/ckx/ckx/node_modules/rethinkdb/ast.js:1046:7)
    at
/Users/stian/src/wallcology/ckx/ckx/node_modules/horizon/src/set-schema.js:205:14
    at new Func
(/Users/stian/src/wallcology/ckx/ckx/node_modules/rethinkdb/ast.js:3386:17)
    at Function.<anonymous>
(/Users/stian/src/wallcology/ckx/ckx/node_modules/rethinkdb/ast.js:3977:12)
    at Function.expr
(/Users/stian/src/wallcology/ckx/ckx/node_modules/rethinkdb/util.js:43:16)
    at funcWrap
(/Users/stian/src/wallcology/ckx/ckx/node_modules/rethinkdb/ast.js:34:19)
    at Array.map (native)
    at MakeArray.RDBVal.forEach
(/Users/stian/src/wallcology/ckx/ckx/node_modules/rethinkdb/ast.js:853:51)
    at
/Users/stian/src/wallcology/ckx/ckx/node_modules/horizon/src/set-schema.js:203:10
~
```

**Comment by danielmewes** [comment]
Ok that looks like a bug in the `--update` implementation now. Sorry about that, we'll look into it.

Pinging @Tryneus
