### ISSUE TITLE
Blog RSS feed

### ISSUE THREAD

**Issue by kaostheory1** [rethinkdb/horizon#417]
Please add RSS feed to your blog:
http://horizon.io/blog/

Thank you!

**Comment by danielmewes** [comment]
@mglukhovsky

**Comment by deontologician** [comment]
I'm going to move this to the internal website tracker, since this isn't related to horizon itself. Thanks for the request @campoviy

**Comment by mglukhovsky** [comment]
The RSS feed is currently available here: https://horizon.io/feed.xml

I'll be adding a more prominent subscription link to the blog soon.
