### ISSUE TITLE
Socket Error OSX 

### ISSUE THREAD

**Issue by apertureless** [rethinkdb/horizon#418]
_OSX_ 10.11.4
_Rethinkdb_ 2.3.2 (CLANG 7.3.0 (clang-703.0.31)) installed over homebrew

Tried to port an existing projekt to horizon, but it wasn't working at all. 
Then I tired the init project:

```
hz init hello-world
```

Started the server with

```
hz serve --dev
```

Admin interface is working. Tables hello-world and hello-world_internal got created.
But the h1 hello world works does not appear.

I am getting some errors: The websocket could not connect.

https://imgur.com/9NqMpGE

```
polling-xhr.js:250 POST http://127.0.0.1:8181/horizon/?EIO=3&transport=polling&t=LJ574tQ&sid=dOHa2JeFbccKvGzDAAAC 400 (Bad Request)o.create @ polling-xhr.js:250o @ polling-xhr.js:163u.request @ polling-xhr.js:91u.doWrite @ polling-xhr.js:104(anonymous function) @ polling.js:208(anonymous function) @ browser.js:325u @ index.js:23(anonymous function) @ browser.js:340(anonymous function) @ browser.js:320e.encodePacket @ browser.js:119o @ browser.js:319o @ browser.js:338s @ browser.js:345e.encodePayload @ browser.js:324n.write @ polling.js:207n.send @ transport.js:108n.flush @ socket.js:550n.sendPacket @ socket.js:610n.write.n.send @ socket.js:570c @ socket.js:63I.next @ socket.js:143e._next @ Subject.js:117e.next @ Subject.js:77e.__tryOrUnsub @ Subscriber.js:225e.next @ Subscriber.js:174e._next @ Subscriber.js:124e.next @ Subscriber.js:88e.notifyNext @ OuterSubscriber.js:19e._next @ InnerSubscriber.js:23e.next @ Subscriber.js:88e._finalNext @ Subject.js:128e._next @ Subject.js:120e.next @ Subject.js:77(anonymous function) @ socket.js:231t.subscribe @ Observable.js:52(anonymous function) @ socket.js:107r.emit @ index.js:134n.onOpen @ socket.js:396n.onHandshake @ socket.js:464n.onPacket @ socket.js:426(anonymous function) @ socket.js:258r.emit @ index.js:134n.onPacket @ transport.js:143r @ polling.js:145(anonymous function) @ browser.js:592e.decodePayloadAsBinary @ browser.js:591e.decodePayload @ browser.js:359n.onData @ polling.js:149(anonymous function) @ polling-xhr.js:124r.emit @ index.js:134o.onData @ polling-xhr.js:285o.onLoad @ polling-xhr.js:366hasXDR.r.onreadystatechange @ polling-xhr.js:238
es6.symbol.js:150 WebSocket connection to 'ws://127.0.0.1:8181/horizon/?EIO=3&transport=websocket&sid=dOHa2JeFbccKvGzDAAAC' failed: Connection closed before receiving a handshake response
polling-xhr.js:250 GET http://127.0.0.1:8181/horizon/?EIO=3&transport=polling&t=LJ574tf&sid=dOHa2JeFbccKvGzDAAAC 400 (Bad Request)o.create @ polling-xhr.js:250o @ polling-xhr.js:163u.request @ polling-xhr.js:91u.doPoll @ polling-xhr.js:121n.poll @ polling.js:119n.onData @ polling.js:158(anonymous function) @ polling-xhr.js:124r.emit @ index.js:134o.onData @ polling-xhr.js:285o.onLoad @ polling-xhr.js:366hasXDR.r.onreadystatechange @ polling-xhr.js:238
index.js:66 Received an error: Error: Websocket ws://127.0.0.1:8181 experienced an errort @ index.js:66e.__tryOrUnsub @ Subscriber.js:225e.error @ Subscriber.js:186e._error @ Subscriber.js:127e.error @ Subscriber.js:101e._error @ ConnectableObservable.js:115e.error @ Subscriber.js:101e._finalError @ Subject.js:149e._error @ Subject.js:136e.error @ Subject.js:97e.__tryOrUnsub @ Subscriber.js:225e.error @ Subscriber.js:186e._error @ Subscriber.js:127e.error @ Subscriber.js:101(anonymous function) @ socket.js:82r.emit @ index.js:134n.onError @ socket.js:670(anonymous function) @ socket.js:261r.emit @ index.js:134n.onError @ transport.js:65(anonymous function) @ polling-xhr.js:108r.emit @ index.js:134o.onError @ polling-xhr.js:296(anonymous function) @ polling-xhr.js:243
polling-xhr.js:250 POST http://127.0.0.1:8181/horizon/?EIO=3&transport=polling&t=LJ574vR&sid=dOHa2JeFbccKvGzDAAAC 400 (Bad Request)
```

Tested with latest node version 6.2.0 and 5.11.0

**Comment by steelbrain** [comment]
+1 hitting the same error
My CLI params are

```
hz serve --secure no --auto-create-collection --auto-create-index --allow-unauthenticated --permissions no --connect localhost:28015 --debug
```

What I see in the terminal is

```
WARNING: Serving app insecurely.
App available at http://127.0.0.1:8189
Starting Horizon...
debug: Added HTTP handler at /horizon/horizon.js
debug: Added HTTP handler at /horizon/horizon.js.map
debug: Added HTTP handler at /horizon/auth_methods
info: Connecting to RethinkDB: localhost:28015
debug: Connection to RethinkDB established.
debug: running metadata sync
info: Groups metadata synced.
info: Index metadata synced.
info: Collections metadata synced.
debug: adding admin user
debug: redirecting users table
debug: metadata sync complete
info: Metadata synced with database, ready for traffic.
Horizon ready for connections 🌄
```

(yep, no error about the connections or anything)
and what I see in browser dev tools is 
<img src="https://cloud.githubusercontent.com/assets/4278113/15373474/addabce8-1cfa-11e6-8f3c-945f88babf26.png">

**Comment by danielmewes** [comment]
Could you run `hz serve` with the `--debug` option please and see if it prints any message when refreshing the website?

**Comment by apertureless** [comment]
After refreshing I get

```
Horizon ready for connections 🌄
debug: Handling HTTP request to horizon subpath: horizon.js
debug: Client connection established.
debug: Closing client connection with message: No connection to the database.
debug: info: {"error":"No connection to the database."}
debug: Client connection terminated.
debug: Handling HTTP request to horizon subpath: horizon.js.map

```

However the admin interface is working and the tables are created.

**Comment by danielmewes** [comment]
@apertureless Ah, what is `hz version`? We fixed a similar issue in Horizon 1.0.1 yesterday.

**Comment by apertureless** [comment]
Installed it yesterday, but still got 1.0.0
Will update and report back.

**Comment by steelbrain** [comment]
@danielmewes I am running `v1.0.1` by the way

**Comment by danielmewes** [comment]
@steelbrain Ah and you were already running with `--debug`, I missed that.
It's weird that you're not even getting any of the "debug: Handling HTTP request" outputs from `hz serve`. Does refreshing the page generate no debug messages at all?

**Comment by steelbrain** [comment]
@danielmewes Not really, It not showing anything, not even that handling HTTP request one

**Comment by danielmewes** [comment]
Pretty odd. Is this just the default application generated by `hz init`? If not, could you share the application code?

**Comment by steelbrain** [comment]
I could share the `config.toml`, here it is https://gist.github.com/steelbrain/5f0f01948110eaf719813aae30c05a20

**Comment by danielmewes** [comment]
```
                                                                                  Thanks, I was more curious about how you were importing the Horizon client into the application and how you're establishing the Horizon connection.
```

**Comment by steelbrain** [comment]
@danielmewes Good catch, to future visitors, I was using a local copy of monkey-patched horizon client to fix a promise bug. Pointing the `<script />` to the horizon server's script path fixed it

**Comment by danielmewes** [comment]
Ah nice, I think we can close this then.

@apertureless please re-open if you're still seeing this issue after the 1.0.1 upgrade.

**Comment by yankeeinlondon** [comment]
I'm getting the same error message in `1.1.1` (updated today) but it may have a different underlying cause. When I run in debug mode I get a number of errors from the database:

> debug: Connection to RethinkDB terminated: ReqlOpFailedError: cannot subscribe to table `api_internal.groups`: primary replica for shard ["", +inf) not available in:
> r.db("api_internal").table("groups").changes({"squash": true, "includeInitial": true, "includeStates": true, "includeTypes": true})
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> debug: stack: ReqlOpFailedError: cannot subscribe to table `api_internal.groups`: primary replica for shard ["", +inf) not available in:
> r.db("api_internal").table("groups").changes({"squash": true, "includeInitial": true, "includeStates": true, "includeTypes": true})
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     at ReqlOpFailedError.ReqlError [as constructor](/usr/local/lib/node_modules/horizon/node_modules/rethinkdb/errors.js:23:13)
>     at ReqlOpFailedError.ReqlRuntimeError [as constructor](/usr/local/lib/node_modules/horizon/node_modules/rethinkdb/errors.js:90:51)
>     at ReqlOpFailedError.ReqlAvailabilityError [as constructor](/usr/local/lib/node_modules/horizon/node_modules/rethinkdb/errors.js:167:56)
>     at new ReqlOpFailedError (/usr/local/lib/node_modules/horizon/node_modules/rethinkdb/errors.js:178:52)
>     at mkErr (/usr/local/lib/node_modules/horizon/node_modules/rethinkdb/util.js:177:10)
>     at TcpConnection.Connection._processResponse (/usr/local/lib/node_modules/horizon/node_modules/rethinkdb/net.js:152:16)
>     at TcpConnection.Connection._data (/usr/local/lib/node_modules/horizon/node_modules/rethinkdb/net.js:122:12)
>     at Socket.<anonymous> (/usr/local/lib/node_modules/horizon/node_modules/rethinkdb/net.js:683:32)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:188:7)
>     at readableAddChunk (_stream_readable.js:172:18)
>     at Socket.Readable.push (_stream_readable.js:130:10)
>     at TCP.onread (net.js:542:20)
> debug: Connection to RethinkDB established.
> debug: running metadata sync
> info: Index metadata synced.
> debug: Connection to RethinkDB terminated: ReqlOpFailedError: cannot subscribe to table `api_internal.collections`: primary replica for shard ["", +inf) not available in:
> r.db("api_internal").table("collections").changes({"squash": true, "includeInitial": true, "includeStates": true, "includeTypes": true})
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> debug: stack: ReqlOpFailedError: cannot subscribe to table `api_internal.collections`: primary replica for shard ["", +inf) not available in:
> r.db("api_internal").table("collections").changes({"squash": true, "includeInitial": true, "includeStates": true, "includeTypes": true})
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     at ReqlOpFailedError.ReqlError [as constructor](/usr/local/lib/node_modules/horizon/node_modules/rethinkdb/errors.js:23:13)
>     at ReqlOpFailedError.ReqlRuntimeError [as constructor](/usr/local/lib/node_modules/horizon/node_modules/rethinkdb/errors.js:90:51)
>     at ReqlOpFailedError.ReqlAvailabilityError [as constructor](/usr/local/lib/node_modules/horizon/node_modules/rethinkdb/errors.js:167:56)
>     at new ReqlOpFailedError (/usr/local/lib/node_modules/horizon/node_modules/rethinkdb/errors.js:178:52)
>     at mkErr (/usr/local/lib/node_modules/horizon/node_modules/rethinkdb/util.js:177:10)
>     at TcpConnection.Connection._processResponse (/usr/local/lib/node_modules/horizon/node_modules/rethinkdb/net.js:152:16)
>     at TcpConnection.Connection._data (/usr/local/lib/node_modules/horizon/node_modules/rethinkdb/net.js:122:12)
>     at Socket.<anonymous> (/usr/local/lib/node_modules/horizon/node_modules/rethinkdb/net.js:683:32)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:188:7)
>     at readableAddChunk (_stream_readable.js:172:18)
>     at Socket.Readable.push (_stream_readable.js:130:10)
>     at TCP.onread (net.js:542:20)
> debug: Connection to RethinkDB established.
> debug: running metadata sync
> info: Groups metadata synced.
> info: Index metadata synced.
> info: Collections metadata synced.
> debug: adding admin user
> debug: redirecting users table
> debug: metadata sync complete
> info: Metadata synced with database, ready for traffic.
> Horizon ready for connections 🌄

**Comment by yankeeinlondon** [comment]
I reset the database and it appears now that my JWT token was expired. Is this something I am meant to manually manage or shouldn't this be done as part of the Horizon housekeeping? 

> Note: this is in "dev" mode and in an unauthenticated area

**Comment by danielmewes** [comment]
@ksnyde Sorry for the late response. I think this was addressed by https://github.com/rethinkdb/horizon/issues/554 and should now work automatically as of Horizon 1.1.1.

**Comment by yankeeinlondon** [comment]
Great, thanks.
