### ISSUE TITLE
TypeError: e is not a constructor

### ISSUE THREAD

**Issue by steelbrain** [rethinkdb/horizon#421]
I am hitting this in latest horizon v1.0.1
<img src="https://cloud.githubusercontent.com/assets/4278113/15376200/5f0f97a6-1d08-11e6-85a8-0d0a45fe60ad.png">
As a workaround, saving the horizon client js locally and replacing that `e` with `Promise` fixes this

**Comment by danielmewes** [comment]
This looks similar to the RxJS Observable definition of `forEach` from client/node_modules/rxjs/src/Observable.ts:

``` js
  /**
   * @method forEach
   * @param {Function} next a handler for each value emitted by the observable
   * @param {PromiseConstructor} [PromiseCtor] a constructor function used to instantiate the Promise
   * @return {Promise} a promise that either resolves on observable completion or
   *  rejects with the handled error
   */
  forEach(next: (value: T) => void, PromiseCtor?: typeof Promise): Promise<void> {
    if (!PromiseCtor) {
      if (root.Rx && root.Rx.config && root.Rx.config.Promise) {
        PromiseCtor = root.Rx.config.Promise;
      } else if (root.Promise) {
        PromiseCtor = root.Promise;
      }
    }

    if (!PromiseCtor) {
      throw new Error('no Promise impl found');
    }

    return new PromiseCtor<void>((resolve, reject) => {
      const subscription = this.subscribe((value) => {
        if (subscription) {
          // if there is a subscription, then we can surmise
          // the next handling is asynchronous. Any errors thrown
          // need to be rejected explicitly and unsubscribe must be
          // called manually
          try {
            next(value);
          } catch (err) {
            reject(err);
            subscription.unsubscribe();
          }
        } else {
[...]
```

But it's either from a different version, or something went wrong in the uglification.

Pinging @deontologician

**Comment by deontologician** [comment]
Hi @steelbrain, what kind of setup are you using? `hz init` `hz serve --dev` or integrating it into an existing app?

**Comment by steelbrain** [comment]
I am integrating into an existing app, but that output is straight from the horizon script from the horizon server, initiated by `hz serve` and got from `/horizon/horizon.js` on version `1.0.1`. Because the original script was minified 3-4 lines, I have beautified it using chrome dev tools to give a better view of the error

**Comment by artisonian** [comment]
Are you passing a second param to `forEach()`? If so, that's why `e` isn't a constructor. I assume you may be doing something like: `collection.fetch().forEach()` and passing two functions rather than `collection.fetch().subscribe()`. Am I correct?

**Comment by steelbrain** [comment]
It could be, I am not sure though, I'll be able to confirm in a few hours

**Comment by steelbrain** [comment]
@artisonian By your last comment, Can you please recommend a proper way of iterating over the items fetched without subscribing and still handling the errors?

**Comment by deontologician** [comment]
@steelbrain you should use subscribe, it takes the usual 3 callbacks. In rxjs 5, they changed how forEach works. It now returns a promise. So you could do:

``` js
someQuery.watch().forEach(x => doSomething(x)).catch(err => handleError(err))
```

**Comment by steelbrain** [comment]
Awesome, Thanks! 👍
