### ISSUE TITLE
Multiple databases for one Fusion server

### ISSUE THREAD

**Issue by danielcompton** [rethinkdb/horizon#43]
The application we're building has one database per tenant. This makes moving our customers from our hosting to self hosting fairly trivial as we only have to move the DB and a copy of the proxy server onto infrastructure that they control. It looks like the database connection in Fusion is a global parameter set per server, not per connection. Is this something that would be able to go into a per connection config (with a default database specified perhaps)?

This also needs to interact with the security API, perhaps part of the connection grant could be checking if the user is authorised for this database.

One alternative for us is to run one Node server per customer. This is possible, but not ideal and will get a bit messy managing host:port config for all of them. It might also be possible to run middleware for each customer, but again that will be a bit messy.

**Comment by deontologician** [comment]
We have this in 1.0, `project_name` can be set in your config.toml to allow multiple databases.

**Comment by danielcompton** [comment]
@deontologician does this let us access multiple databases from the same running Node instance? `project_name` lets you switch databases, but doesn't appear to support multiple at the same time?

**Comment by deontologician** [comment]
From the same node instance, yes. From the same horizon server instance, no. You'll need to make one horizon server instance for each app, and attach them separately to either multiple http server instances, or to the same instance under different paths.

I could be wrong that this currently works, @Tryneus correct me if I'm wrong
