### ISSUE TITLE
Add pre-publish script

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/horizon#431]
It should do a couple things, suggested by @danielmewes in https://github.com/rethinkdb/horizon/pull/430#issuecomment-220206951

It should:
- [ ] Check for uncommitted files in the current directory

Some other nice to haves might be automatically tagging in git with the version number, and maybe some other checklist items

Edit: removed second checkbox

**Comment by danielmewes** [comment]
My original suggestion was actually just for the first part. A positive list always comes with the risk of forgetting files in the package, which also sucks.

We can use `git status | grep -q "working directory clean"` to check for any uncommitted files (though in the whole repository, not just the current directory).

**Comment by deontologician** [comment]
Ok, removed the second checkbox

**Comment by marshall007** [comment]
`npm version` might save some work. It checks for uncommitted files in the working directory before updating the `package.json`, committing, and tagging the commit.

**Comment by deontologician** [comment]
This is done in 2.0.0. It handles changing deps
