### ISSUE TITLE
[Docs] Horizon Client

### ISSUE THREAD

**Issue by hnordt** [rethinkdb/horizon#433]
In http://horizon.io/docs/getting-started/ the docs say:

> However, if you’re using [Webpack][] or a similar build setup, or requesting the .js library at load time isn’t desirable, just add the client library as an NPM dependency (npm install @horizon/client).
> 
> In your application, you’ll need to include the Horizon client file, and specify the Horizon port number when initializing the connection.

``` js
<script src="localhost:8181/horizon/horizon.js"></script>

// Specify the host property for initializing the Horizon connection
const horizon = Horizon({host: 'localhost:8181'});
```

`In your application, you’ll need to include the Horizon client file, and specify the Horizon port number when initializing the connection.` shouldn't be `In your application, you’ll need to import the Horizon client file, and specify the Horizon port number when initializing the connection.`?

Also the code shouldn't be:

``` js
import Horizon from '@horizon/client';

// Specify the host property for initializing the Horizon connection
const horizon = Horizon({host: 'localhost:8181'});
```

?

**Comment by deontologician** [comment]
I've migrated this issue to our docs repo here: rethinkdb/horizon-docs#57
