### ISSUE TITLE
Docs at https://www.npmjs.com/package/horizon seem old

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/horizon#435]
It looks like the documentation on that page is from an older version.  (For example, it lists `--insecure` instead of `--secure`.)

**Comment by dalanmiller** [comment]
Now that we have horizon.io and the RethinkDB/horizon-docs repo, we need to
decide what to do with the outdated readmes and documentation in the
Horizon repo.

**Comment by mglukhovsky** [comment]
@dalanmiller: have we removed stale documentation? We should update the README to point exclusively to the official docs.

**Comment by deontologician** [comment]
I think this is fixed
