### ISSUE TITLE
Error when calling horizon.authEndpoint() on client

### ISSUE THREAD

**Issue by appmark** [rethinkdb/horizon#446]
Tried to use OAuth in horizon, but I'm getting error when I call
`horizon.authEndpoint('github').then((endpoint) => {})`
It successfully fetches:
`/horizon/auth_methods`
But then I get error in browser console:
`auth.js:19 Uncaught TypeError: (0 , b.default)(...).do is not a function`

**Comment by deontologician** [comment]
So this seems to be an issue with fetchJSON not being defined. Not sure how this broke, but it should be simple to fix
