### ISSUE TITLE
Check Existence

### ISSUE THREAD

**Issue by hnordt** [rethinkdb/horizon#451]
Hello.

I tried to use `fetch()` to check for existence, but it doesn't worked, any ideas?

``` js
// Doesn't work, neither callback dispatches
calls.find({ from: 'hnordt' }).fetch()
  .subscribe(r => console.warn(r), e => console.error(e))
```

**Comment by danielmewes** [comment]
A work-around is using the final callback with a local variable like this:

``` js
let foundCall = false;
calls.find({ from: 'hnordt' }).fetch()
  .subscribe(() => { foundCall = true; console.log("Call existed"); }, (e) => console.error(e), () => {
    if (!foundCall) {
      console.log("Call did not exist");
    }
  });
```

We should come up with an API for providing a nicer way of detecting non-existence.

Maybe `find` should call the result callback with `null` if no row exists?

**Comment by hnordt** [comment]
@danielmewes that would be what I expected initially. Awesome.

**Comment by deontologician** [comment]
I think this is the best way to do it. We could potentially return null, but I think this works better with observable operators. For example, if you do

``` js
require('rxjs/add/operator/isEmpty')

calls.find({ from: 'hnordt' }).fetch().isEmpty().subscribe(
 empty => console.log('It was', empty? ' ' : ' not', 'empty')
)
```

**Comment by danielmewes** [comment]
Oh I forgot there were all those nice Observable operators.

One point in favor of generating a `null` is that it makes it easier to throw an error if a document _should_ exist but doesn't.

@deontologician Is there an option to "split" an Observable stream? Like what if I want to use the result, but do something different if it's empty?

**Comment by marshall007** [comment]
@danielmewes [`.partition()`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/partition.md) will split an observable sequence into two observable streams based on some condition. There's also [`.defaultIfEmpty()`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/defaultifempty.md) which is probably the way to go in this case.

**Comment by danielmewes** [comment]
Cool, `defaultIfEmpty()` sounds like what I wanted. We should probably add an example with that do our docs.

@hnordt Does that satisfy your use case?

**Comment by hnordt** [comment]
@danielmewes yes, thank you!
