### ISSUE TITLE
hz init should add a .gitignore file

### ISSUE THREAD

**Issue by encryptio** [rethinkdb/horizon#454]
`.hz/config.toml` is not intended to be committed as it contains secrets, and `rethinkdb_data` is also not intended to be committed.

When `hz init` runs, it should add a `.gitignore` file ignoring these.

**Comment by deontologician** [comment]
I've thought of this before, it's probably a good idea, but some people don't use git

**Comment by jordandenison** [comment]
how about something like `--scm git` to generate it?

**Comment by encryptio** [comment]
I think if you put it behind a (non-default) flag, people just won't use the flag because they won't know about it, and adding documentation about it where people _will_ see it probably makes it harder for new users to grok what's happening overall. In other words, the users we want to protect with this (users who aren't yet familiar with what goes in these files) won't be able to benefit from the protection.

**Comment by jordandenison** [comment]
Actually the secrets in `.hz/config.toml` can be replaced by environment variables, so not everyone is going to want that in their `.gitignore` anyways.  Probably best to leave it out completely.

**Comment by dalanmiller** [comment]
I'd like to propose getting this in for Horizon 2.0, not everyone uses `git` but is there a compelling reason as to why having a loose `.gitignore` in the directory would hurt? I just refound this issue as I noticed `rethinkdb_data` was being picked up in my horizon test app's directory

**Comment by deontologician** [comment]
sounds good to me
