### ISSUE TITLE
Insufficient appreciation error, thank you overflow. 

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/horizon#456]
https://discuss.horizon.io/t/thank-you-horizon-v1-0-0/126

Thank you to all of you who contributed to the Horizon project in one form or another, we at RethinkDB couldn't have done it without all of you. 

@flipace
@marshall007
@plievone
@ChrisCates
@mbseid
@chrisabrams
@cancan101
@rosskukulinksi
@blamy
@thinklinux
@stevenmathews
@janders223
@robstolarz
@crapthings
@catkins
@hnordt
@mkaulig
@artisonian
@aarmora
@nivoc
@helixten
@tikotzky
@djedi
@snickell
@amarth1982
@demohi
@cletusw
@ingro
@kamilshahzad
@zijua
@den-t
@intellix
@voodooattack
@nor-bu
@vijaysimhajoshi
@Rajan
@klikstermkd
@mehdi-cit
@nyrosmith
@kerbelp
@marksteve
@rizafahmi
@natew
@ncammarata
@nbostrom
@chrisabrams
@kriskowal
@chrisvariety
@ha1331
@natew

**Comment by ChrisCates** [comment]
Thanks man. Let me know when you wanna collab/skype about the rethinkdb pitch... I figure Mike and Slava should be involved to at this point.

Also I am 100% pushing Horizon once changefeeds are supported on relational joins. There's just too much goodness coming out of RethinkDB.

Cheers Daniel.

---- On Thu, 19 May 2016 20:26:23 -0400 Daniel Alan Miller &lt;notifications@github.com&gt;wrote ---- 

https://discuss.horizon.io/t/thank-you-horizon-v1-0-0/126

Thank you to all of you who contributed to the Horizon project in one form or another, we at RethinkDB couldn't have done it without all of you. 

@flipace

 @marshall007

 @plievone

 @ChrisCates

 @mbseid

 @chrisabrams

 @cancan101

 @rosskukulinksi

 @blamy

 @thinklinux

 @stevenmathews

 @janders223

 @robstolarz

 @crapthings

 @catkins

 @hnordt

 @mkaulig

 @artisonian

 @aarmora

 @nivoc

 @helixten

 @tikotzky

 @djedi

 @snickell

 @amarth1982

 @demohi

 @cletusw

 @ingro

 @kamilshahzad

 @zijua

 @den-t

 @intellix

 @voodooattack

 @nor-bu

 @vijaysimhajoshi

 @Rajan

 @klikstermkd

 @mehdi-cit

 @nyrosmith

 @kerbelp

 @marksteve

 @rizafahmi

 @natew

 @ncammarata

 @nbostrom

 @chrisabrams

 @kriskowal

 @chrisvariety

 @ha1331

 @natew
