### ISSUE TITLE
Client terminantes the connection upon an illegal write/read

### ISSUE THREAD

**Issue by vramana** [rethinkdb/horizon#458]
Steps to reproduce:
- Start a horizon server (not in dev mode) with an empty schema without any collections.
- Connect to the server as authenticated user.
- Execute the following code on the client

``` js
var messages = horizon('messages')
messages.store({ a: 1 })
```

Expected behaviour:

Client throws an error with message `Collection "messages" does not exist`

What happens:

In addition to throwing the error, the client closes the connection.

Client Version: 1.0.1
Server Version: 1.0.1

**Comment by vramana** [comment]
I don't see this behaviour in the 2.0.0-beta5 version. Probably this bug is fixed. If somebody else could confirm this, this issue can be closed.

**Comment by deontologician** [comment]
We should add a test for this

**Comment by deontologician** [comment]
Going to close since no one else has reported this
