### ISSUE TITLE
Init call allows hyphens in the project name, which results in errors on `hz serve`

### ISSUE THREAD

**Issue by bradledford** [rethinkdb/horizon#460]
When creating new applications using the `hz init...` command and you include a hyphen in the project name, the resulting boilerplate application cannot be started. This is due to the fact that RethinkDB does not allow hyphens (or special characters) in the database name, as hinted at in the regex mentioned below.

When calling `hz serve --dev` in the resulting app directory (containing the hyphen), Horizon just emits a message like the following over and over until it times out:
`error: Connection to RethinkDB terminated: ReqlQueryLogicError: Database name hzDemo-2 invalid (Use A-Za-z0-9_ only) in:
r(["hzDemo-2", "hzDemo-2_internal"]).forEach(function(var_6) { return r.branch(r.dbList().contains(var_6), [], r.dbCreate(var_6)); }).do(function() { return r(["collections", "users_auth", "users", "groups"]).forEach(function(var_7) { return r.branch(r.db("hzDemo-2_internal").tableList().contains(var_7), [], r.db("hzDemo-2_internal").tableCreate(var_7)); }); })`

A possible solution would be to warn, fairly strongly, when calling hz init that any project names not matching the required A-Za-z0-9_ pattern is invalid or just deny it altogether.

**Comment by danielmewes** [comment]
Thanks for the report @bradledford . This is close to https://github.com/rethinkdb/horizon/issues/376 and we're going to fix this soon. Closing as a duplicate.
