### ISSUE TITLE
[Getting Started] Docs reference a non-existent option to hz init

### ISSUE THREAD

**Issue by nwwells** [rethinkdb/horizon#463]
```
> hz version
1.0.1
```

The [getting started docs](http://horizon.io/docs/getting-started/) reference an option `auto-create-table`, which I think should be `auto-create-collection`

**Comment by danielmewes** [comment]
Thanks for reporting this @nwwells .

I fixed the docs via https://github.com/rethinkdb/horizon-docs/commit/c1b0292ab4a9597938786e0710863229309d02ff . We're going to publish the updated website soon.

(in the future, you can report documentation-related issues directly at https://github.com/rethinkdb/horizon-docs/issues )
