### ISSUE TITLE
My first experience

### ISSUE THREAD

**Issue by christianalfoni** [rethinkdb/horizon#465]
Hi there!

Just want to start out saying I am extremely excited about this project, fantastic work! :-)

I went through the getting started and working on larger apps I of course have a build workflow, using webpack mostly.

There were a couple of things that confused me:
1. The name `@horizon/client` is not very common. It would be nice in the getting started to see an example of how you actually import it as well. Just threw me off a bit
2. When I got it running I got an error :

``` js
ERROR in ./~/@horizon/client/lib/util/fetch.js
Module not found: Error: Cannot resolve module 'imports' in /Users/christianalfoni/Development/temp/example_app/node_modules/@horizon/client/lib/util
 @ ./~/@horizon/client/lib/util/fetch.js 13:0-69
```

After installing it manually I got the error:

``` js
ERROR in ./~/@horizon/client/lib/util/fetch.js
Module not found: Error: Cannot resolve module 'exports' in /Users/christianalfoni/Development/temp/example_app/node_modules/@horizon/client/lib/util
 @ ./~/@horizon/client/lib/util/fetch.js 13:0-69
```

After installing again I got the error:

``` js
ERROR in Loader /Users/christianalfoni/Development/temp/example_app/node_modules/exports/lib/exports.js?global.fetch didn't return a function
 @ ./~/@horizon/client/lib/util/fetch.js 13:0-69
```

Checking the source code I get a feeling these were actually the `imports-loader` and `exports-loader` from webpack, so installed those instead.

And then it worked :-)

I would say this is some package dependency stuff that needs to be resolved rather than documentation? If not I would be happy to help.

**Comment by flipace** [comment]
hi @christianalfoni good to see you around! :)

This issue is already resolved in the next branch and will be fixed in the next release of horizon!
Yes, it was a incorrectly set dependency.

**Comment by christianalfoni** [comment]
Ah, that is great! Thanks for the quick response and keep up the great work! :)
