### ISSUE TITLE
Setting allow_anonymous=true and allow_unauthenticated=false in config.toml doesn't work

### ISSUE THREAD

**Issue by nphyatt** [rethinkdb/horizon#467]
When I set the config.toml file of the server to:

```
allow_anonymous = true
allow_unauthenticated = false
```

and try to connect from client with:

```
var horizon = Horizon({host: 'localhost:8181', authType: 'anonymous'});
```

I can't connect and get the following output from the server:

```
debug: Received handshake: {"method":"token","token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJ1c2VyIjpudWxsLCJwcm92aWRlciI6bnVsbCwiaWF0IjoxNDYzNzYzMTQ5LCJleHAiOjE0NjM4NDk1NDl9.b9dXNZHz3RlWD3lEA6dugzMrlRg0DgTfqsg1vCNFbNEc4ISalDExRRa92USe1a-e6mhyCpwDwq3uzVIH4148gw","request_id":0}
debug: Closing client connection with message: Error: Unauthenticated connections are not allowed.
debug: info: {"request_id":0,"error":"Error: Unauthenticated connections are not allowed.","error_code":0}
debug: Client connection terminated.
```

**Comment by danielmewes** [comment]
The debug output shows that the server got a handshake with the `"token"` authType, not `"anonymous"`. Can you post the server output for the `authType: 'anonymous'` version?

**Comment by danielmewes** [comment]
You might also need to run `Horizon.clearAuthTokens()` in your browser's JavaScript console to clear out the existing token.

**Comment by nphyatt** [comment]
`Horizon.clearAuthTokens()` took care of it. Thanks!

**Comment by danielmewes** [comment]
@deontologician Shouldn't an authentication failure like this clear the stored token automatically btw?

**Comment by deontologician** [comment]
It should, but @Tryneus fixed a bug in the server yesterday that closed the connection before sending the error back, so we were never learning the reason for the failure.
