### ISSUE TITLE
Allow unsubscribing from all requests in the client

### ISSUE THREAD

**Issue by Tryneus** [rethinkdb/horizon#470]
At the moment, it appears we can only unsubscribe from `subscribe` requests in the client.  While this makes sense at first glance, `end_subscription` is implemented more generically in the server, and can be used to close any request.

I propose we allow `unsubscribe` on any request observable, which will send an `end_subscription` for that request, then ignore any subsequent responses for the given `request_id`.  This is particularly useful when users want to extend Horizon with custom request types which may involve cursors or changefeeds.

Also, we should probably rename `end_subscription` in the protocol to `close_request` or `stop_request` or something.

In the future, the server could be more proactive about cancelling requests, such as interrupting reads or writes in the database using `STOP` in the ReQL protocol, although the impacts of that should be carefully considered.

**Comment by stellanhaglund** [comment]
Does this allow me to unsubscribe and close the cursor from the client?

Im strugggling with closing the cursors when i change route in angular, im able to unsubscribe but it doesnt close the cursor

**Comment by Tryneus** [comment]
@stellanhaglund - if you define custom request types that use cursors or feeds, this should allow you to close that request from the client by calling `unsubscribe` on the observable for that request.

**Comment by stellanhaglund** [comment]
I do that and i can see isSubscribed is false, but the cursor still seems
to be there, when i trigger a change on that feed i see it logged on the
server anyway, and if i do the same request several times and unsubscribe
them i see logs from then trigger a change the feed is triggered the same
amount of times.

Ive been able to get to different states, one is the above, another is that
the feed closes when i refresh the page and the last one is that its closes
directly when the initial values are done.

The last one doesnt happen if i dont send the done.

So it seems a little like i wouldnt like the done to be triggered until i
unsubscribe, and when done is sent feed.close() will run.
Or am i going about it the wrong way?

torsdag 26 maj 2016 skrev Tryneus notifications@github.com:

**Comment by deontologician** [comment]
On the server end there may not be an unsubscribe callback by default

**Comment by stellanhaglund** [comment]
do you mean this?

```
return () => {
    if(feed){
        feed.close()
    }
}
```

I'm using that and I have tried adding it in many different forms in all places of my code but the only outcomes I get is those three I mentioned above.

**Comment by stellanhaglund** [comment]
The problem for me seems to be that depending on what processing is made in my endpoint, I don't know where to put `done` it's either closing to soon, or it's not closing at all..

**Comment by stellanhaglund** [comment]
Couldn't the endpoint be completely cleaned up when calling unsubscribe and using sendRequest?

**Comment by deontologician** [comment]
ping @Tryneus for these difficult questions :D
