### ISSUE TITLE
watch() results expose `$hz_v$` version field

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/horizon#476]
As of Horizon 1.0.2, it seems like `watch()` results don't filter the `$hz_v$` field from documents. With `fetch()` the field gets removed properly.

@deontologician

**Comment by sachinbhutani** [comment]
the store() function also exposes $hz_v$ field in subscribe, although documentation says it should return id only, Not sure if it's a defect or intended ?

**Comment by danielmewes** [comment]
I'm not sure either what the intended behavior for `store()` and other writes was. @Tryneus and @deontologician might have some insights on this.

**Comment by deontologician** [comment]
We intend to have the version field available in write operation results, not in reads. This is a bug in the client

**Comment by Tryneus** [comment]
@sachinbhutani - write responses are meant to have the `$hz_v$` field in them, so the local data can be kept up-to-date in case clients need to restrict writes to only apply to a specific version.  I believe at some point we will need an option for reads to include the version field for specific applications.

The `protocol.md` was a little out-of-date, so I updated it in 0263e21.  The structure was correct, but the description was old.
