### ISSUE TITLE
Proposal: Remove non-printing Emoji from startup

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/horizon#478]
There is a large subset of users for whom it doesn't print, and it's not at all clear from context what it means.

The first time I started the Horizon server I actually thought it was an error, and went to find Daniel to see why the server was bugging out.  (I was on OS X using iTerm2 with the DejaVu Sans Mono font, so it isn't just a problem on Linux.)

In my particular case it rendered as a question mark with a black background, which I think is especially confusing.  People who work on the project know that it's just a non-printing character, but for people using Horizon for the first time I think it's a really ugly wart -- it's not clear what the character is supposed to mean, why it's there, or what information they're missing by not seeing it.

(It's especially bad in cases like http://stackoverflow.com/questions/37349843/rethinkdb-horizon-after-some-usage-getting-400-bad-request-errors-resulting-i where the server prints some errors before displaying the weird non-printing character.)

Ping @Tryneus, @coffeemug, @danielmewes, @deontologician, @dalanmiller .

**Comment by danielmewes** [comment]
Since I've installed the appropriate fonts, the emoji does look pretty nice.

However it being rendered as a question mark is indeed not great, as it might look like a status indication.

I'm in slight favor of removing it, but don't feel strongly about this issue.

**Comment by deontologician** [comment]
What if we add a flag like `--strip-emoji-for-mlucy` ?

**Comment by deontologician** [comment]
More seriously, we could just move the emoji to the beginning of the line, where it's less likely to be mistaken for punctuation

**Comment by danielmewes** [comment]
Data point in favor of keeping an emoji: https://twitter.com/foxteck/status/736043597594693632

I think moving it to the beginning of the line would be a definite improvement.

**Comment by encryptio** [comment]
I think OSX is the only case where you can assume the terminal and font set are capable of handling the emoji by default; I suspect @mlucy's problem comes from sticking emacs/eshell in the middle (but correct me if I'm wrong.)

It doesn't generally work on Linux without installing non-default font packages (on both Archlinux and Ubuntu at least), and I have no idea about terminals on Windows.

Perhaps only printing if [`process.platform`](https://nodejs.org/api/process.html#process_process_platform) equals `"darwin"` would be a good middle ground, keeping pretty characters only where it's likely to work.

**Comment by dalanmiller** [comment]
> Perhaps only printing if process.platform equals "darwin" would be a good middle ground, keeping pretty characters only where it's likely to work.

I was hoping this effort would slowly die and make Linux users fight for their emoji rights 🗽, but if the check is really this simple, then I propose we add this and call it good. @mlucy is this a sufficient resolution?

**Comment by deontologician** [comment]
Moved it to the beginning of the line

**Comment by deontologician** [comment]
I didn't do the `== darwin` solution because I use arch and it would prevent me from seeing it :P
