### ISSUE TITLE
Problems with Webpack-bundling and `import`ing client-side

### ISSUE THREAD

**Issue by mtchllbrrn** [rethinkdb/horizon#484]
I'm trying to get Horizon working with Webpack and `'@horizon/client'` in the browser.  The problem is that... nothing occurs when initiate the connection then attempt to store a document. 

This example repo reproduces the issue: https://github.com/mtchllbrrn/horizon-webpack

I expect Line 4 of `index.jsx` to insert a document to the collection, but checking the collection with the Rethink browser UI shows that nothing happens. No errors are thrown at any point in the process.

I'm using v1.0.1 of the Horizon server and Webpack is bundling v1.0.2 of the Horizon client.

**Comment by hturan** [comment]
For what it's worth, I was having trouble with Webpack bundling the client last night using 1.0.2 of `@horizon/client` and `@horizon/server`. Listening to `status` events showed no signs of life or error in the client.

I didn't delve deep enough to see what was happening, but solved it by completely skipping importing `@horizon/client` and just using the static file from the server (`<script src="/horizon/horizon.js"></script>`) and treating `Horizon` as a `window` global.

It's clear that `import Horizon from '@horizon/client'` results in a different `Horizon` object than simply using the static `horizon.js` file as a global, but I'm not sure why, and I'm unsure in exactly how they differ. Will update here when I get a chance to dig into it.

**Comment by flipace** [comment]
I'm experiencing the same issue. It seems to be some kind of dependency problem or so. It seems like the clients `socket.subscribe()` is not initializing a connection to the server (neither via socket or xhr).

Related issue in lovli.js: https://github.com/flipace/lovli.js/issues/8

Weirdest part is that it works just fine if I npm link `@horizon/client` from an up to date cloned `next` branch...

**Comment by mbeaudru** [comment]
Experiencing the same issue here  :+1: it's very weird that there aren't any error

**Comment by flipace** [comment]
Okay, I found the culprit! It's the latest beta version of rxjs which breaks the client.

`npm i rxjs@5.0.0-beta.7` fixes the problem for now.

I think that, as long as rxjs 5 is in beta, it shouldn't be required with ^ but as a fixed version.
Everytime they publish a new version it could break the horizon client - which is not a good thing.

PS: https://github.com/ReactiveX/rxjs/blob/master/package.json rxjs@5.0.0-beta.8 is the latest version.

**Comment by mbeaudru** [comment]
Solved the problem for me, bravo!
