### ISSUE TITLE
Uncaught TypeError: horizon.authEndpoint(...).toPromise is not a function(…)

### ISSUE THREAD

**Issue by lyonzy** [rethinkdb/horizon#485]
Hello,

I've grabbed 1.0.2 and my last issue #462 seems to be fixed, but I'm getting this:

`Uncaught TypeError: horizon.authEndpoint(...).toPromise is not a function(…)`

Perhaps it's missing an import or something?

In the meantime, I'm working around it by just going `window.location.pathname = '/horizon/twitter'`.

Cheers,
Matt

**Comment by danielmewes** [comment]
@lyonzy It's an issue with the documentation (we have a fix for it that we'll publish soon https://github.com/rethinkdb/horizon-docs/pull/66/files ). `toPromise` is actually not available on the result of `authEndpoint`.

Try this code instead:

``` js
horizon.authEndpoint('twitter').subscribe((endpoint) => {
  window.location.pathname = endpoint;
});
```

**Comment by lyonzy** [comment]
Ah great, yep that works a dream. Cheers :)
