### ISSUE TITLE
setting connect in .hz/config.toml changes port but host is always localhost

### ISSUE THREAD

**Issue by nphyatt** [rethinkdb/horizon#486]
Setting `connect = host:port`  will change port but the host is always localhost according to --debug output.

**Comment by danielmewes** [comment]
Thanks for reporting this @nphyatt.
Sounds like a bug either in the server or in the CLI.

Pinging @Tryneus

**Comment by Tryneus** [comment]
Fixed in PR #499 - thanks for reporting this, @nphyatt!

**Comment by nphyatt** [comment]
Thanks for the quick response and fix @Tryneus and @danielmewes!
