### ISSUE TITLE
Configuration options to specify db and table name 

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/horizon#494]
@mfferreira brings up a good point at https://discuss.horizon.io/t/support-for-existing-rethinkdb-database/173.

I think that one should be able to add configuration to specify the db and table name used by the Horizon server. This will allow people with already existing tables and databases who can't move them or would be inconvenienced to move them into a horizon-made table. 

```
#Possible option for database name "already" and table name "existing"
hz serve --dev --db already --table existing
```

Is there any meta-data that would have to be generated for each document in the table if using a pre-existing db.table?

**Comment by deontologician** [comment]
I think in addition, you'd have to detect indices etc from the existing tables, so #120 is related

**Comment by deontologician** [comment]
We allow you to specify the db name now (the project name), so this is effectively resolved. #120 has the rest of the behavior I think
