### ISSUE TITLE
Horizon appends random string to table names

### ISSUE THREAD

**Issue by natew** [rethinkdb/horizon#498]
Adding after discussion on #horizon, basically it's a bit strange to add the hash after table name when using horizon (harder to use vanilla rethinkdb now).

**Comment by deontologician** [comment]
ping @Tryneus

**Comment by mglukhovsky** [comment]
After discussing this, we're going to remove the random strings from table names.

This was originally added to prevent multiple Horizon servers (running in development mode with `auto_create_collection`) from entering a race condition on the table names, but we're planning to add a lock on the `horizon_internal` metadata database.

**Comment by Tryneus** [comment]
This has been fixed by #685.  Now there is a race condition in the case of multiple horizon servers for the same project with `auto_create_collection` enabled, but that will be addressed once rethinkdb/rethinkdb#5987 is available in ReQL.
