### ISSUE TITLE
server side variables

### ISSUE THREAD

**Issue by ha1331** [rethinkdb/horizon#50]
Had a chat with @danielmewes, he said I should write this. To keep this short, pretty much what the topic says. Would be pretty cool to have server side variables. Obvious example that comes to mind would be what r.now() is in ReQL. Timestamps are tricky because if you don't have "neutral clock", times you use are pretty much what users have set their clocks to. So the precision, even without having someone passing nonsense on purpose, would be pretty low.

**Comment by danielmewes** [comment]
How similar is this to https://github.com/rethinkdb/horizon/issues/194 ? Should we consolidate these two issues?

**Comment by danielmewes** [comment]
Actually the final proposal in https://github.com/rethinkdb/horizon/issues/194#issuecomment-214886239 seems to be equivalent to this. Even though this issue is older, #194 has seen some more discussion so I'm going to close this in favor of #194.
