### ISSUE TITLE
Subscribe() suppresses errors

### ISSUE THREAD

**Issue by mattcodez** [rethinkdb/horizon#500]
Server: 1.0.2 
Client: Whatever that server version sends

So, I was having a recurring error in a `subscribe()` callback but had no way of knowing. Even adding an error callback does nothing. Some trimmed code from my application:

```
hz.currentUser().fetch().subscribe(user => {
      console.log('hi');
      throw 'test';
      console.log('foo');
    }, err => console.error(err), ()=>console.log('done!'));
```

Results in 'hi' being logged in the console but nothing else and no errors being thrown in Chrome 50. Note, code is being eval()'ed after a Babel transpile.

**Comment by danielmewes** [comment]
Note that `subscribe` is a method from RxJS: http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-subscribe

Their documentation doesn't seem to specify how exceptions thrown in one of the callbacks are handled, so I'm not sure if this is intended behavior from their side or not.

**Comment by marshall007** [comment]
@mattcodez see ReactiveX/rxjs#1135. Errors thrown in the `next` callback are not propagated to the subscription's `error` handler. As an alternative, you can use `.forEach` which returns a Promise and is rejected when any error is thrown on the subscription or in the `next` callback.

``` js
hz.currentUser().fetch().forEach(user => {
  console.log('hi');
  throw 'test';
  console.log('foo');
})
.catch(err => console.error(err))
.then(() => console.log('done!'))
```

If you prefer a solution that only uses Observables, you can use the `.do()` operator in place of the `next` handler:

``` js
hz.currentUser().fetch().do(user => {
  console.log('hi');
  throw 'test';
  console.log('foo');
})
.subscribe(null, err => console.error(err), () => console.log('done!'))
```
