### ISSUE TITLE
The Positioning Problem for Horizon Framework

### ISSUE THREAD

**Issue by Rajan** [rethinkdb/horizon#505]
I've been watching horizon and also played with it a bit.
It seems more like a co-framework to me than a standalone framework so far.
Is it how it's positioned? or It can be used independently of other Node.js frameworks.
If it can be used independently, why don't we have some framework-independent examples?

**Comment by danielmewes** [comment]
Horizon is indeed not a full standalone framework and is not intended to be (unlike Meteor for example). Instead Horizon concentrates on the functionality that you would typically implement in your backend, such as data storage, push updates, authentication, security and a few other components.

This is why http://horizon.io/ talks about a "JavaScript backend", not "framework". Is there a section on the website that you think we should clarify to make this more obvious?

We intentionally didn't reinvent the wheel by providing layout and rendering infrastructure with Horizon, but instead made it extremely easy to integrate with any existing framework of your choice.

**Comment by Rajan** [comment]
You could but making this clear isn't enough.
A developer wanting to build something would be ideally looking for:
- A web development framework which does the complete job: sails.js, meteor, rails etc.
- Mobile Backend As A Service: Firebase, Strongloop Loopback, backendless etc.
- Individual components for various use cases for a framework: push, auth, redis etc. Most frameworks have also their own versions of components for these!

Even if you make it clear, it'd be hard for a sizable audience to search and understand "Javascript Backend" or the meaning of it. One way to solve this discoverability issue is by creating various npm/other components the way the strongloop loopback does it. There may be better ideas though!

**Comment by danielmewes** [comment]
Thanks for sharing your thoughts.

Horizon quite closely fits the second category ("Mobile backend as a service"). The "as a service" part is optional with Horizon (well, right now it's not even available yet, but we're working on changing that. Look out for "Horizon Cloud"). It also is not limited to mobile apps, but neither are the other services you list as far as I can tell. I think once Horizon Cloud is available, Horizon will more obviously fit that niche.

We'll hopefully have a lot of additional documentation and examples soon that describe how you can use individual components of Horizon within an existing framework, which will hopefully help discoverability as well.

I wonder if splitting things up into individual NPM packages is an option or if there are technical challenges with that. (@deontologician @Tryneus)

@coffeemug might have some more thoughts on increasing the discoverability of Horizon.

**Comment by joshwiens** [comment]
@Rajan - This makes perfect sense. In essence it is a self hosted `backend as a service` which allows for integration and transition to a more robust API when you need to extend the functionality.

We don't need another framework, we need a simple way to get data from a DB into an Application that can step out of the way when a more robust server implementation is required.

As an aside, basing a design off of something like loopback is a tragically bad idea. This is intended to be simple with a graceful transition and not some bloated enterprise-tastic all-in-one solution.

**Comment by deontologician** [comment]
Going to close since it's not a bug, but feel free to discuss here or on our discourse forum: https://discuss.horizon.io

As far as splitting things into npm packages, I think we should do that as the design process naturally spins off independent chunks. It's definitely the node/js way to break things out into smaller units (both for code size reasons and just culturally), so it makes sense to move things into independent packages over time. We just want to make sure the interfaces we're creating are good abstractions before committing to them by making them a public api.

**Comment by deontologician** [comment]
A good example where the module -> public api discussion is going on is #428
