### ISSUE TITLE
Integrate with Auth0 (OAUTH2 meta-authentication provider)

### ISSUE THREAD

**Issue by garthk** [rethinkdb/horizon#518]
Further to @dweldon's comment on #176:

> Integrating with a meta-authentication provider like [auth0](https://auth0.com/) could be really useful.

Auth0's back end [identity providers](https://auth0.com/docs/identityproviders) include:
- Most of the OAUTH2 social providers you'd expect
- ADFS, Active Directory, LDAP, and SAML-P for enterprise SSO
- Password-less authentication via email, SMS, and the iOS touch sensor
- Auth0's own cloud identity service
- The database of your choice

That, plus a free tier for 7K users across Auth0's database plus 1-2 social providers, could reduce the urgency to hook up all of the above. It'd certainly make life easier for me. ツ

**Comment by deontologician** [comment]
This sounds reasonable. I think we should probably work on getting something like #428 first so that it's easier to build 3rd party modules to different auth types

**Comment by deontologician** [comment]
This was done in #601  and #733
