### ISSUE TITLE
Examples: Oauth + react + react-router

### ISSUE THREAD

**Issue by thinklinux** [rethinkdb/horizon#534]
A lot of people are searching for that particular example. Should I try and make something this weekend or are you guys on it already? :)

**Comment by deontologician** [comment]
Have at it, I don't think we have anything in the works for this

**Comment by ramstein74** [comment]
Dont forget Vuejs , like horizon, a litle above mainstream, react or
angular..

2016-05-27 22:43 GMT+01:00 Josh Kuhn notifications@github.com:

**Comment by eh3rrera** [comment]
Hi, I wrote a tutorial about how to integrate React, React Router, Horizon.io with OAuth authentication, and Express. Maybe you can find it useful:
http://tutorials.pluralsight.com/interesting-apis/building-a-real-time-application-with-react-react-router-horizon-io-and-oauth
The Github repo:
https://github.com/eh3rrera/react-horizon

**Comment by bartekus** [comment]
@eh3rrera thank you for making this wonderful example however it is no longer operational as recent changes cause it to throw `e is not a constructor` and `WebSocket Ctor is not a constructor` error on Messages screen.

**Comment by eh3rrera** [comment]
Thank you @Bartekus, I'll update it.
