### ISSUE TITLE
defaultIfEmpty() problem

### ISSUE THREAD

**Issue by hnordt** [rethinkdb/horizon#541]
When I try to use `defaultIfEmpty()` with Horizon 1.0.3 I receive this error:

```
TypeError: (0 , _horizon2.default)(...).find(...).fetch(...).defaultIfEmpty is not a function(…)
```

My code:

``` js
import Horizon from '@horizon/client'
import 'rxjs/add/operator/defaultIfEmpty'

const horizon = Horizon()

horizon('contacts')
  .find(1)
  .fetch()
  .defaultIfEmpty({})
  .subscribe(contact => console.warn(contact)
```

**Comment by deontologician** [comment]
I am guessing this is an issue with which `Observable` is getting patched. It's likely there are two Observable classes, one provided and used by the Horizon client, and one provided and patched here by the rxjs library I'm assuming you've packaged.

This is the reasoning behind #306 , which would mean you'd bring your own Observable, and that way things like this would just work.

**Comment by deontologician** [comment]
I think I'm going to try to solve this as part of #532 , but I'll leave this open to make sure it gets fixed explicitly
