### ISSUE TITLE
Hostname validation is too strict

### ISSUE THREAD

**Issue by steelbrain** [rethinkdb/horizon#545]
This is an error I get when I launch horizon, I am on the latest version (v1.0.2), here's the screenshot of the error

<img src="https://cloud.githubusercontent.com/assets/4278113/15724382/a29fbb24-27fb-11e6-92ad-779b99982683.png">

As you can see it says `internal_db` is an invalid hostname, it is however a very valid hostname. I am using horizon on docker where this hostname is updated by docker with the latest ip of the rethinkdb container, it's working fine in all the other apps, only horizon seems to be thinking it's an error.

Admittably it's a bug in `joi`, but since I use horizon not joi, I figured I should open an error here. Also opening bug in it's repo

**Comment by steelbrain** [comment]
Also opened https://github.com/hapijs/joi/issues/908

**Comment by danielmewes** [comment]
Maybe we should remove the Joi hostname check in our code until this is fixed upstream.

**Comment by steelbrain** [comment]
The bug was closed in joi mainly because this hostname works almost everywhere but is not valid according to the RFC. To make things work I renamed `internal_db` to `internal-db`
