### ISSUE TITLE
Proposal: change internal database naming scheme

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/horizon#546]
@Tryneus told me that if you have a project `foo`, we currently create two databases `foo` and `foo_internal`.  This naming scheme is kind of bad, because if a user has two projects `bar` and `bar_internal`, the internal database for the first project and the non-internal database for the second project will conflict.

Another problem is that we aren't namespacing these databases, which makes it hard for them to coexist with other databases that might already be in people's RethinkDB cluster.  (For example, if you have data in the `test` database, which is very common, then having a project named `test` will be in the same place.)

I'd like to propose that instead of `foo` and `foo_internal`, we have `hz_foo` and `hzinternal_foo`.  That solves the first problem and also makes conflicts much much less likely (as well as allowing people to have projects named `rethinkdb`).

**Comment by deontologician** [comment]
This was resolved in 2.0.0, we now have `hz_` prefixed secret tables in the app database.
