### ISSUE TITLE
Unrecognized auth provider "0" when using HZ_AUTH environment variable

### ISSUE THREAD

**Issue by jephir** [rethinkdb/horizon#560]
Server version: horizon@1.0.2

I am trying to use the **HZ_AUTH** environment variable instead of _.hz/config.toml_ to configure OAuth authentication to avoid committing provider secrets to my source code repository. However this results in an error:

```
WARNING: Serving app insecurely.
App available at http://0.0.0.0:8181
Starting Horizon...
debug: Added HTTP handler at /horizon/horizon.js
debug: Added HTTP handler at /horizon/horizon.js.map
debug: Added HTTP handler at /horizon/auth_methods
serve failed with Error: Unrecognized auth provider "0"
    at /usr/src/app/node_modules/horizon/src/serve.js:562:17
    at process._tickCallback (node.js:369:9)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3
```

``` sh
$ echo $HZ_AUTH
google,<REMOVED>.apps.googleusercontent.com,<REMOVED>
```

_.hz/config.toml:_

``` toml
bind = [ "all" ]
port = 8181
project_name = "horizon"
token_secret = <REMOVED>
allow_anonymous = true
allow_unauthenticated = false
```

If I enter the google authentication options into the _[auth.google]_ section in _.hz/config.toml_ then there is no error.

**Comment by Tryneus** [comment]
Hi @jephir, sorry about the delay.  While this is the format you use on the command-line, it is slightly different when specifying via environment variables.  For your example, you would export `HZ_AUTH_GOOGLE_ID=<REMOVED>.apps.googleusercontent.com` and `HZ_AUTH_GOOGLE_SECRET=<REMOVED>`.  I added PR #605 to warn when we are ignoring an auth environment variable when the path doesn't match - and to avoid writing it into the options.

**Comment by deontologician** [comment]
Closing since this doesn't seem to be a bug
