### ISSUE TITLE
Running horizon on EC2

### ISSUE THREAD

**Issue by fortm** [rethinkdb/horizon#562]
I am setting up EC2 instance with horizon for testing purposes
`hz serve --dev`
starts application but in localhost:8181
I tried to add --bind IP --port 8181
but continue to get below error - 
`HTTP server: Error: listen EADDRNOTAVAIL IP:8181`

**Comment by deontologician** [comment]
This looks like the address `IP:8181` is invalid. Where are the instructions coming from for these?

**Comment by deontologician** [comment]
I am going to close for now, since this looks like a configuration issue with EC2, feel free to reopen if you think there's actually a bug with Horizon here.
