### ISSUE TITLE
Horizon can't connect to a rethinkdb proxy server

### ISSUE THREAD

**Issue by alf** [rethinkdb/horizon#564]
- Server version: 2.3.3, windows
- Client version: https://github.com/ericb/horizon/commit/f3a2284ff0e1ca011ca88fc22048d8f793262c9b

In the reql_connection.js, there is an assumption that the server id exists in the server_status table. This is not correct if the server we are connecting to is a proxy.

**Comment by deontologician** [comment]
Nice catch

**Comment by danielmewes** [comment]
@Tryneus Is this something that can be fixed easily?

**Comment by Tryneus** [comment]
Fixed by PR #597.  Thanks for reporting this, @alf!
