### ISSUE TITLE
Token no longer stored in localStorage

### ISSUE THREAD

**Issue by hswolff** [rethinkdb/horizon#568]
Server version: `2.3.4`
Client version: `1.1.1`

When I try to instantiate Horizon with `Horizon({authType: 'anonymous'})` I don't see any token's stored in `localStorage`.

I compared this behavior to client version `1.0.2` and I saw the token saved in `localStorage`.

I believe it was this PR that caused this regression: https://github.com/rethinkdb/horizon/pull/556

**Comment by deontologician** [comment]
See https://github.com/rethinkdb/horizon/pull/556#discussion_r66391507 It looks like I have the logic backwards for this :/

**Comment by deontologician** [comment]
Also reported by @Bekt in https://github.com/rethinkdb/horizon/issues/570#issue-159045781

> Screencast: http://recordit.co/wsIahMz2KE
> 
> Hey, the docs say the JWT token is stored in localStorage, but that doesn't seem to be the case. Please see the recording above.
> 
> Horizon version: `1.1.1`
> Code: [index.html](http://pastebin.com/Q26iPTHW)

**Comment by mardo** [comment]
@deontologician 
I think this PR solves the issue. I tested locally and it stores the session :)

https://github.com/rethinkdb/horizon/pull/579

**Comment by hswolff** [comment]
Woohoo! Awesome! TY!
