### ISSUE TITLE
JWT token is not being stored

### ISSUE THREAD

**Issue by Bekt** [rethinkdb/horizon#570]
Screencast: http://recordit.co/wsIahMz2KE

Hey, the docs say the JWT token is stored in localStorage, but that doesn't seem to be the case. Please see the recording above.

Horizon version: `1.1.1`
Code: [index.html](http://pastebin.com/Q26iPTHW)

**Comment by hswolff** [comment]
FYI https://github.com/rethinkdb/horizon/issues/568

**Comment by Bekt** [comment]
Ah, very nice. I should have tested previous versions as well.

cc @deontologician

**Comment by deontologician** [comment]
Sorry you guys ran into this, we should be able to address it Thursday

**Comment by deontologician** [comment]
Ok, closing this one as a dupe of #568 , @Bekt thanks for the screencast and demo code, I've ported your comment over to the other issue
