### ISSUE TITLE
Example config file in CLI README has wrong defaults and is outdated

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/horizon#578]
https://github.com/rethinkdb/horizon/blob/next/cli/README.md#hzconfigtoml-file has multiple issues:
1. It's outdated. The `insecure` flag is now called `secure`, and the `auto_create_table` flag is now called `auto_create_collection`.
2. It has wrong defaults. The default for `secure` is `yes`, `serve_static` is undefined or false by default, and the auto_create options are `no` by default as well.

It is probably better to link to http://horizon.io/docs/configuration/

**Comment by danielmewes** [comment]
@dalanmiller

**Comment by dalanmiller** [comment]
All good!
