### ISSUE TITLE
Change the entrypoint for the Horizon client in package.json

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/horizon#581]
The entrypoint for the Horizon client is currently `lib/index.js`, which is the unprocessed Webpack configuration, whereas it should probably be `dist/horizon.js`.

We should also figure out why `lib/index.js` contains unprocessed directives.

**Comment by deontologician** [comment]
After sorting out the webpack stuff, it turns out lib/index.js is the entrypoint we want. The major issue was that we had a fetch directive in a require statement which is bad.
