### ISSUE TITLE
On install Horizon or a dependency is confused by local Sinopia repo/registry setting

### ISSUE THREAD

**Issue by kushalj** [rethinkdb/horizon#582]
Node 4.4.3
Npm 2.x.x and 3.x.x

my ~/.npmrc contains my sinopia registry details:

```
registry=http://mydomain.com/npm
//mydomain.com/:_authToken="NONSENSEAUTHTOKEN"
```

and this seems to have prevented horizon from installing. I finally removed the lines temporarily. installed Horizon, and put them back.

Not had this before; no idea what is causing it. The debug was no useful except to show me that it was searching my repo and couldn't find horizon.

I once got "no such package : @horizon/server", then upgrade npm to 3+ and got "no such package : npm" ???

**Comment by deontologician** [comment]
Is your registry fully synced with the global npm registry? Maybe it doesn't have the packages or is not able to sync scoped packages

**Comment by kushalj** [comment]
The registry is from my work place and only has local, private packages. Other packages are fetched from global npm. I have to be honest, I don't know how this works. I just assumed it fetches from npmjs if the package is not found locally on our servers.

**Comment by deontologician** [comment]
You might want to talk to whoever manages your synopia installation, it looks like scoped packages were added in version 1.0.0: https://github.com/rlidwka/sinopia/issues/104

**Comment by deontologician** [comment]
Closing since this doesn't seem to be a horizon issue
