### ISSUE TITLE
Allow passing a Websocket API compatible object to Horizon

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/horizon#584]
We should allow the user to provide their own WebSocket implementation to Horizon. This will allow different transports, as long as they are websocket compatible.

Since we're going to move to RxJS's version of websocketsubject (#276) this issue is blocking on that one.

**Comment by plievone** [comment]
This seems like a very good idea, for the client side, and possibly also the server side if possible. Immediate use could be in testing client side situations such as errors and reconnections, as mocking the implementation with special error cases would be simpler than building a proxy server that would break the actual websocket connections in reliable ways.

For a baseline implementation, one needs to be able to set handlers as `.onerror`, `.onopen`, `.onmessage` and `.onclose`, to read `.readyState` with states 0,1,2,3 (and perhaps read constants `CONNECTING = 0`, `OPEN = 1`, `CLOSING = 2`, `CLOSED = 3`), and call `.send` and `.close`. A bit tricky is to provide correct error and close events (with `code`, `wasClean`, `reason`), but the tests could document the actually depended on interface. A similar approach was taken in RxJS websocket tests: see [mock](https://github.com/ReactiveX/rxjs/blob/master/spec/helpers/ajax-helper.ts#L3-L99) and [tests](https://github.com/ReactiveX/rxjs/blob/master/spec/observables/dom/webSocket-spec.ts).

**Comment by plievone** [comment]
I drafted a quick client side mock with some comments here:
https://gist.github.com/plievone/4ee0987839f1b470a39871f62190c7be

**Comment by deontologician** [comment]
I'm working on #276 at the moment since it'll fix some other bugs in our websocket implementation (probably #595 for example), so this may overlap with this issue too.

How is the mock intended to be used?

**Comment by plievone** [comment]
That gist is just a barebones websocket mock (but proxying to real websocket, so not really a mock, more like a "Websocket API compatible constructor"), and one can use it in place of ordinary websocket (`new MockWebSocket(path)` etc). It could be passed to those RxJS websocket subjects to be used as a websocket constructor, and tweaked to conform to the actually depended on websocket interface. From Horizon's point of view the main question is how to handle close codes with transports that don't provide them.

Earlier this year I looked into RxJS5 WebSocketSubject and earlier WebSocket observable, which was the base for HorizonSocket, but despite them being from the same author, it looked like they had quite a different way of wiring things up, which different semantics for closing etc. There's also a curious comment about ["a proper Operator/Subscriber implementation [eliminating] closures"](https://github.com/ReactiveX/rxjs/blob/bf54db4/src/observable/dom/WebSocketSubject.ts#L70), perhaps we could make it happen somehow?

**Comment by deontologician** [comment]
I saw that comment too, I think it could probably become an operator, it seems I implemented basically the same thing on top of it (we multiplex by the request_id)

**Comment by deontologician** [comment]
This is going to be fixed by #276

**Comment by deontologician** [comment]
Fixed in #619
