### ISSUE TITLE
error when setting config option in toml file

### ISSUE THREAD

**Issue by cybor0** [rethinkdb/horizon#585]
hz serve --dev
C:\Users..\horizon\src\serve.js:328
      throw new Error(`Unknown config parameter: "${field}".`);
      ^

Error: Unknown config parameter: "groups".

[groups.default.rules.read_current_user]
template = "collection('users').find({id: userId()})"

**Comment by deontologician** [comment]
This should be in a separate schema.toml file, not in the config.toml

**Comment by cybor0** [comment]
Ok thx
