### ISSUE TITLE
Distributed code should not contain webpack specific logic

### ISSUE THREAD

**Issue by nphyatt** [rethinkdb/horizon#590]
There is a require statement in the client https://github.com/rethinkdb/horizon/blob/next/client/src/util/fetch.js#L6 which is webpack specific and therefore when I attempt to build using typescript I come up against the following error:

```
Error: Cannot find module 'imports?this=>global!exports?global.fetch!isomorphic-fetch' from '/Users/home/demo/node_modules/@horizon/client/lib/util'
```

**Comment by imhoffd** [comment]
Anyone using horizon's `main` entry in `package.json` (`lib/index.js`) and building their own bundle is essentially forced to use webpack with this line.

**Comment by deontologician** [comment]
Hey guys, we're going to fix this as soon as possible. We are a little backed up at the moment, so bear with us.

**Comment by flipace** [comment]
I'm going to work on this today so it should be fixed with the next release. Sorry for the troubles :(

**Comment by flipace** [comment]
here's the pr: https://github.com/rethinkdb/horizon/pull/593
