### ISSUE TITLE
Remove all polyfills and document which features Horizon uses

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/horizon#600]
It's been suggested we should just remove all polyfills. The ones we include are convenient (ish) since they allow a user to get started with Horizon without having to also import a bunch of shims, but at the same time it seems like something a library you import shouldn't do for you. In other words, which polyfills to use is probably an app-level decision, not a library decision.

I'm not entirely sure if this is a good or bad idea, but discussing it seems reasonable

**Comment by intellix** [comment]
Stumbled upon this on my travels: https://cdn.polyfill.io/v2/docs/
It supposedly polyfills everything for you automatically as you need. Haven't looked too deep into it though. Just figured it's something easy enough to add to the app-level

**Comment by deontologician** [comment]
Yeah, if we do this it would be nice to point app developers at something convenient like that

**Comment by fallenpeace** [comment]
Why not make them opt-in, opt-out via the Hz CLI?

Seems to be the best world. As I for one have been using horizon, without ever noticing I had to "polyfill" I  like that horizon has it built in sorta how meteor has its polyfills built in for the most part. 

Because like you said, the point of horizon is to get started right away.

**Comment by deontologician** [comment]
I think our current build system solves the problem this issue was opened to fix. We offer `horizon.js` which is the all-in-one package with Rx and polyfills, and `horizon-core.js` is the version where you bring your own polyfills and Rx.

In addition, we got rid of fetch, which was one of the major polyfills we relied on

Closing for now
