### ISSUE TITLE
Horizon doesn't support moment.js

### ISSUE THREAD

**Issue by alf** [rethinkdb/horizon#606]
Client version: 1.1.1

When horizon serializes an object it seems that it first serializes date objects to horizon date objects.

A moment object from http://momentjs.com contains a date object which is converted in the above pass. This causes the moment to be invalid and thus an exception is raised.

**Comment by deontologician** [comment]
This would be nice to implement, but I think moment.js can output plain js Date objects right?

**Comment by alf** [comment]
Yes, it's not hard to work around. It's surprising behaviour though. :)

**Comment by jeveloper** [comment]
moment can output UTC time and also timestamp very easily , that's probably the best way to store date time without enforcing any particular format

**Comment by intellix** [comment]
Related to #635. I guess it doesn't have anything to do with moment.js. Problem is that it's mutating date objects into metadata

**Comment by alf** [comment]
Closing in favour of #635 which cuts to the heart of the problem.
