### ISSUE TITLE
Horizon schema validator doesn't fire any event

### ISSUE THREAD

**Issue by akanass** [rethinkdb/horizon#608]
Hello,
- Server version => 1.1.3
- Client version =>  version from server at `/horizon/horizon.js`

I create some validators in my schema and I want to store data from client but if my data doesn't match validator, storage will be not performed but no error will be fired from the server.

How I can know that my client data doesn't match with server validator?

Thanks.

**Comment by deontologician** [comment]
ping @Tryneus

**Comment by deontologician** [comment]
Since this is a question, I've ported it to the discussion board here: https://discuss.horizon.io/t/getting-errors-from-schema-validators/355 . If a bug is discovered in answering it, we can open another issue for it.
