### ISSUE TITLE
Set hub.docker.com/r/rethinkdb/horizon to use 2.x.x

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/horizon#616]
We need to do this upon releasing 2.0

**Comment by reactivize** [comment]
What's the ballpark ETA for v2, and an official docker image?

p.s.
Keep up the good work guys.

**Comment by dalanmiller** [comment]
Hey @reactivize!

We are ​currently only building branches `next` and `1.x.x` which go into image tags ​​`:next` and `:latest` respectively. 

If you want bleeding edge, definitely `docker pull rethinkdb/horizon:next`. But I'd also wait until #603 gets merged in and that will be our official image (under `:latest`). Also would love any feedback you have on them! 

We want to get Horizon 2.0 out as soon as possible, I would reckon with the next two months.

**Comment by reactivize** [comment]
Thanks @dalanmiller,

I'll wait for that merge then I'll start testing out the Horizon docker image.
I'd like to design and publish a useful end-to-end starterkit template, utilizing, rethinkDB, graphQL, reactJs, and docker, that gets a dev machine up and running quick.

**Comment by dalanmiller** [comment]
For now @reactivize you can just use the `:next` and be okay 👍 . I'll ping back here though once we release a new version of Horizon (and those commits get merged into `1.x.x`)

**Comment by deontologician** [comment]
@dalanmiller is this a pre-2.0 todo item or is it an issue that can be closed before the release?

**Comment by dalanmiller** [comment]
We should do this the moment 2.x.x is available on `npm`, whatever makes sense.

**Comment by deontologician** [comment]
:+1:
