### ISSUE TITLE
Cannot connect when embedding horizon to existing project.

### ISSUE THREAD

**Issue by alikhani** [rethinkdb/horizon#627]
Hi,
Wanted to try out horizon so I'm trying to embed horizon to an existing react/express-project but can't get the horizon-client to connect to the horizon-server due to a socket-issue..?
<img width="1278" alt="horizon-issue" src="https://cloud.githubusercontent.com/assets/1507144/16562608/1900e5e2-41fe-11e6-80c9-62eab9478533.png">

server.js

``` javascript
const httpServer = app.listen(port, (err) => {
  if (err) {
    return logger.error(err.message);
  }
});
const options = {
    project_name: 'insight',
    auth: { 
      token_secret: 'my_super_secret_secret',
    }
};

const horizonServer = horizon(httpServer, options);
```

client:

``` javascript
import Horizon from '@horizon/client';
...
componentDidMount() {
    const horizon = Horizon({ authType: 'anonymous' });
    horizon.connect();
}
...
```

Server version: 1.1.3
Client version: 1.1.3

**Comment by deontologician** [comment]
ping @Tryneus 

@alikhani do you have any logs for what the server was seeing to cause the socket error?

**Comment by coltonmorris** [comment]
I get a similar error when trying to embed horizon in express.
![screen shot 2016-07-07 at 5 24 02 pm](https://cloud.githubusercontent.com/assets/6676864/16673017/b2c38e12-4467-11e6-82a4-b5059e686f2f.png)

**Comment by coltonmorris** [comment]
I'm experiencing similar issues.

**Comment by angelbeltran** [comment]
I'm getting a similar error.

`componentDidMount: function () {
  horizon('messages').order('datetime', 'descending').limit(8).watch().subscribe((messages) => this.setState({ messages: messages }))
}`

![screen shot 2016-07-07 at 6 21 09 pm](https://cloud.githubusercontent.com/assets/12766260/16673952/3500de40-4470-11e6-92dc-1bffa548d88f.png)

**Comment by deontologician** [comment]
Ah, ok. This is from engine.io. This is fixed on next, see #525 .

We're hoping to release 2.0 soon with this fix, hang in there :)

**Comment by joshwnj** [comment]
@alikhani @coltonmorris @angelbeltran hopefully this gets fixed in 2.0, but could you also please try with the following settings and let us know if you still see the error?

```
const options = {
  permissions: false,
  auth: {
    allow_anonymous: true,
    allow_unauthenticated: true
  }
}
```

**Comment by angelbeltran** [comment]
The error persists for me, even with those options.

**Comment by mtford90** [comment]
+1

I was facing this but the following allowed me to get started:

index.html:

```
const horizon = Horizon({host: 'localhost:3000', authType: 'unauthenticated'});
```

embedded server:

```
const horizonServer = horizon(httpServer, {
  project_name: 'example_app',
  permissions:  false,
  auth:         {
    token_secret:          'my_super_secret_secret',
    allow_anonymous:       true,
    allow_unauthenticated: true
  }
})
```
