### ISSUE TITLE
Express Application

### ISSUE THREAD

**Issue by sachinsawant71** [rethinkdb/horizon#628]
I am trying to embed Horizon within express application. I used the example server provided here - https://github.com/rethinkdb/horizon/tree/next/examples/express-server.

When I start the app, I get following error 

Connection to RethinkDB terminated: Error: The databases horizon and horizon_internal do not exist. Run `hz set-schema` to initialize the database, then start the Horizon server.

I tried to run hz set-schema but what are the mandatory parameters for it?

**Comment by deontologician** [comment]
Hi @sachinsawant71,

This is a bit annoying at the moment, we have an issue #548 for making this easier. The mandatory parameter is the path to the schema to use, but you may also want to specify where your rethinkdb instance is:

```
usage: hz set-schema [-h] [--project-name NAME] [--connect HOST:PORT]
                     [--start-rethinkdb [yes|no]] [--config PATH]
                     [--debug [yes|no]] [--update [yes|no]] [--force [yes|no]]
                     [project_path] PATH

Positional arguments:
  project_path          Change to this directory before serving
  PATH                  File to get the horizon schema from, use "-" for 
                        stdin.

Optional arguments:
  -h, --help            Show this help message and exit.
  --project-name NAME, -n NAME
                        Name of the Horizon Project server
  --connect HOST:PORT, -c HOST:PORT
                        Host and port of the RethinkDB server to connect to.
  --start-rethinkdb [yes|no]
                        Start up a RethinkDB server in the current directory
  --config PATH         Path to the config file to use, defaults to ".
                        hz/config.toml".
  --debug [yes|no]      Enable debug logging.
  --update [yes|no]     Only add new items and update existing, no removal.
  --force [yes|no]      Allow removal of existing collections.
```

Going to close since this is just a question. Feel free to ask on our message board [discuss.horizon.io](https://discuss.horizon.io/c/get-help)
