### ISSUE TITLE
Fusion Server can become out of sync with RethinkDB instance if table is manually deleted

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/horizon#63]
At the moment Fusion Server stores metadata about collections in the `fusion_internal` database under `collections`. Stopping the server, deleting one of the tables listed there, and then restarting the server does not remove the metadata of that now deleted table from `fusion_internal.collections` and thus it will not attempt to recreate it.

 Not sure about the inverse when deleting the metadata from `fusion_internal.collections` if it will restore it if the table still exists.

**Comment by dalanmiller** [comment]
Closing for now, as this hasn't been an issue.

**Comment by deontologician** [comment]
I think this is superceded by #120
