### ISSUE TITLE
Please expose the reduce RxJS Observable operator

### ISSUE THREAD

**Issue by alf** [rethinkdb/horizon#630]
The fetch and watch methods return RxJS Observables. These observables have a handful of useful operators attached. Unfortunately reduce seems to be missing.

**Comment by alf** [comment]
Since fetch returns all hits in one go and since watch is continous and thus reduce would prevent emitting anything until the stream is closed I guess reduce isn't very useful after all.

**Comment by alf** [comment]
I do need this on the observables returned by store/upsert however. My usecase is that I need to map the generated ids back to the entities I saved. Since store/upsert currently calls the write callback once for each stored document, I need to first reduce this to a list that I can then map against the input list.

I assume that the write callbacks come in the same order as the input documents.

**Comment by alf** [comment]
A workaround for people in the same situation is to use lift with the ReduceOperator:

```
import { ReduceOperator } from 'rxjs/operator/reduce';
[...]
    db.store(items)
      .lift(new ReduceOperator((acc, curr) => acc.push(curr), new List()));
[...]
```

Edit: This workaround seems to break things mysteriously. That is, I seem to have to add a `.map(x => x)` after the lift operation for the chain not to be broken.

**Comment by danielmewes** [comment]
We've had some discussion internally about which operators to include and which not. The trade-off is that between a larger Horizon client on the one hand, and more operators being available out of the box on the other hand.
We previously added back some additional operators, but not `reduce` I think (https://github.com/rethinkdb/horizon/issues/532) .

I think there's a way to "inject" additional operators into the Horizon observables. @deontologician might be able to help with that.

**Comment by danielmewes** [comment]
https://github.com/rethinkdb/horizon/issues/634 also mentions some related points. It suggests including `rx-lite` operators by default as a partial solution. However `rx-lite` does not seem to include `reduce`.
The other points in the issue are about making it easier to add additional operators. That should be useful for this one.

**Comment by alf** [comment]
With rx-lite I guess I can combine `scan` with `takeLast`.

I'll close this issue in favour of #634.
