### ISSUE TITLE
Horizon no longer queues queries run before horizon.onReady has triggered

### ISSUE THREAD

**Issue by alf** [rethinkdb/horizon#631]
According to the [documentation](http://horizon.io/api/horizon/#onready), you don't need to use horizon.onReady before running a query. This worked fine until [this commit](https://github.com/rethinkdb/horizon/commit/ce05382cbcdc8c152d8b9db6faa2621e85893799). After that it seems the queries are silently dropped.

**Comment by alf** [comment]
I'm currently working around this by wrapping my code in hz.onReady. However for this to work I have to manually trigger hz.connect() otherwise my query gets dropped.

**Comment by deontologician** [comment]
This is weird, I am hoping it'll be fixed by #619

**Comment by deontologician** [comment]
@alf, can you see if this works for you on the #619 branch?

**Comment by alf** [comment]
Tried out the #619 branch and it seems to break everything for me. That is I'm no longer able to fetch data and I'm no longer able to store data.

Just to be sure I tested the correct commit: 16b1c31c6464fe2b85ff42f66a4c9778df17853c

I installed it by running the `test/setupDev.sh` script then running `npm link @horizon/client` and server in my repo before packing and testing my code. Maybe I've missed a step?

**Comment by deontologician** [comment]
Ok, you're correct. It is inexplicably not working on that branch. I had it working locally and with CircleCi, so let me figure out what went wrong. Sorry about that

**Comment by deontologician** [comment]
Alright @alf it turns out the bug was upstream. I needed to use a fixed version of WebSocketSubject, which I opened a PR for here: https://github.com/ReactiveX/rxjs/pull/1831

If you're feeling adventurous you might try building with that, otherwise we can wait and see if/when they merge it upstream

**Comment by deontologician** [comment]
Ok, this fix has been merged into next. The rxjs guys haven't had a chance to look at my patch, so I just hacked it into our implementation for the time being. @alf Any chance you could check this out again? (thanks for your patience)

**Comment by deontologician** [comment]
This seems fixed

**Comment by alf** [comment]
I'll look at it when I'm back from vacation. I'm sure it's fine however. :)
