### ISSUE TITLE
`hz.currentUser().fetch()` doesn't call `connect`

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/horizon#633]
If you follow the instructions at https://horizon.io/api/horizon/#currentuser :

```
const hz = new Horizon();
hz.currentUser().fetch().subscribe( (user) => console.log(JSON.stringify(user)) );
```

It doesn't work, but if you call `connect` first it does.

**Comment by danielmewes** [comment]
I think this is a duplicate of https://github.com/rethinkdb/horizon/issues/567
