### ISSUE TITLE
Support Rollup's `jsnext:main` in package.json

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/horizon#637]
It would be nice if we supported rollup. Theoretically, it should be as simple as adding:

``` js
"jsnext:main": "src/index.js"
```

to package.json, but we'd need to try it out with rollup itself

**Comment by deontologician** [comment]
This was done in 2.0.0

**Comment by simoncarpinter** [comment]
See https://github.com/rethinkdb/horizon/pull/820 :)
