### ISSUE TITLE
Horizon ignores the `host` it was passed when fetching `auth_methods`

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/horizon#640]
If I write `hz = Horizon({host: SOME_HOST})`, it still tries to read `localhost:8080/horizon/auth_methods` instead of `host/horizon/auth_methods`.

**Comment by mlucy** [comment]
(This was in 1.1.3.)

**Comment by deontologician** [comment]
This is a dupe of #422 which is slated for 2.0 (I'm probably working on this next since #634 is about done) Also @mlucy would you like to review #634?
