### ISSUE TITLE
Horizon (at least as of 1.1.3) doesn't give you any way to add middleware

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/horizon#641]
I need to turn on CORS for access to `horizon/auth_methods`, and as far as I can tell there's literally no way to do it without hacking it in.

It would be nice of Horizon integrated better with Express so that the Express middleware could run before and after it.  (I'm not sure if that's already the plan or not.)

**Comment by deontologician** [comment]
This is probably subsumed by #24, there's a vague plan to add a middleware api for the server so you can bring your own webstack. In your case it seems like you'd want to use horizon with express and separately use express's middleware

**Comment by deontologician** [comment]
To clarify, the problem right now is that horizon server is taking over certain http endpoints. As part of implementing plugins, I think we're going to move to using express for the cli and having horizon server expose its own request handler, so you'd have complete control over that
