### ISSUE TITLE
`Horizon.authEndpoint('provider')` should include the host name

### ISSUE THREAD

**Issue by mglukhovsky** [rethinkdb/horizon#645]
I was working with a local Horizon instance, and a remote Horizon instance. I was connected to the remote instance as follows:

```
Horizon({
    host: 'my-host.io',
    secure: true,
    authType: 'token'})
```

As the documentation suggest, I called the following to redirect my browser to the OAuth endpoint (from the Horizon server):

```
horizon.authEndpoint('github').subscribe(endpoint => location.pathname = endpoint)
```

I received an endpoint, in this case `/horizon/github`. However, since I was serving my project from the _local_ Horizon instance, my browser redirected to `http://localhost:8181/horizon/github`, when I _really_ wanted it to redirect to `http://my-host.io/horizon/github`.

This was particularly confusing because it ended up using tokens and the Horizon config set up in my _local_ instance for the OAuth flow, when I indicated that my Horizon connection was to a 
_remote_ host.

It would be easier and less error-prone if the client includes the `host` parameter in the endpoint it returns.

**Comment by mglukhovsky** [comment]
The docs would have to be updated to suggest using `location.assign` (which replaces the entire location string) rather than simply `location.pathname` (which will just update the pathname, not the host).

**Comment by deontologician** [comment]
This was done (including the docs update to use location.assign)
