### ISSUE TITLE
horizon client cannot create new Collection

### ISSUE THREAD

**Issue by StefanSchwartze** [rethinkdb/horizon#648]
I'm trying to get horizon working embedded in my koa.js application. I have integrated it like this:

```
const horizon = require('../libraries/horizon/server');
const http_server = server.listen(port);
const horizon_server = horizon(http_server, {
    project_name: 'test',
    auth: { 
        token_secret: 'test', 
        allow_anonymous: true, 
        allow_unauthenticated: true
    },
    permissions: false,
    auto_create_collection: true,
    auto_create_index: true
});

```

It is required from my applications folder because I use the current 2.0.0 version from the next branch. In my client I connected horizon like this:

```
const hz = Horizon();
…

componentDidMount() {
        hz.connect();
        hz.onReady(() => {
            console.log("Connected to Horizon server");

            hz.currentUser().fetch().subscribe( (user) => console.log(JSON.stringify(user)) );
            const users = hz('users');
            users.find({id: "admin"}).fetch().subscribe(msg => console.log(msg));
            const messages = hz('messages');
            messages.store({
                id: 1,
                url: "avatar_url",
                from: "bob",
                text: "Hello from RethinkDB"
            })
            hz("messages").find({from: "bob"}).fetch().subscribe(
                result => console.log('Result:', result)
            );

        });
        hz.onDisconnected(() => console.log("Disconnected from Horizon server"));
}
```

In my React application on the top I'm importing Horizon from my library folder and then in the componentDidMount I'm looking if horizon is ready. This works fine. I've also created an admin user which is found correctly with the Collection API. But when I'm trying to write something in a new Collection called "messages", it says the Collection does not exist and then disconnects the server..

Why can't I create a new collection?

Server version: 2.0.0
Client version: 2.0.0

**Comment by StefanSchwartze** [comment]
Okay, finally got it to work after a lot of research. This [http://tutorials.pluralsight.com/interesting-apis/building-a-real-time-application-with-react-react-router-horizon-io-and-oauth](http://tutorials.pluralsight.com/interesting-apis/building-a-real-time-application-with-react-react-router-horizon-io-and-oauth) helped me at the end, because it is the only page where really it is described how to correctly embed it in an existing application. Please improve your documentation!

**Comment by deontologician** [comment]
Glad you got it working @StefanSchwartze . We're planning on changing how embedding works very soon, so we're holding off expanding the docs for the moment. Sorry you ran into troubles, hopefully after the refactor it'll be significantly easier to do

**Comment by stephenwil** [comment]
That link has gone - can you give a bit more advice, as I'm experiencing this exact issue.

**Comment by StefanSchwartze** [comment]
@stephenwil I've updated my comment, the reference behind the link was not correct. Unfortunately, I can't give more advice because I kicked it because of experiencing too much errors and bugs.

**Comment by stephenwil** [comment]
@StefanSchwartze Thanks

I _want_ to like it, as I like the fact we can consume RxJS subscribables, but the massive differences between the hz serve and embedding the server is wasting lots of time at the moment.

**Comment by deontologician** [comment]
Hey @stephenwil, we're working on this gap at the moment. We know it's a huge pain, so we're looking to make the transition a lot easier in the coming releases.
