### ISSUE TITLE
Extended documentation for the React examples.

### ISSUE THREAD

**Issue by noahtallen** [rethinkdb/horizon#662]
I've noticed there's next to no documentation for getting Horizon set up with React, except for the example apps. It'd be great for beginners if there was a more detailed guide on why / how these examples actually work - as opposed to just putting them there. It's difficult to learn a new technology when the examples/documentation aren't applied in a way that discusses why / how to use Horizon's functions in broad situations. I don't care about creating the specific to-do list app, I want to learn how to use Horizon to build anything!

**Comment by danielmewes** [comment]
Good point, I opened https://github.com/rethinkdb/horizon-docs/issues/101 in the separate horizon-docs repository.

I'm going to close this for now, as we will track and discuss things in the other issue.
