### ISSUE TITLE
Can't install non-global?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [rethinkdb/horizon#665]
I'd like to run the server on Heroku, with the latest code in branch "next" for user/pass connection strings. So I need to install non-globally, and I'm getting some weird errors.

$ npm install github:rethinkdb/horizon#next
npm ERR! addLocal Could not install /var/folders/c2/33k9s6bs35d4p8gldgnl0gxc0000gn/T/npm-43780-79905adc/git-cache-c94d89a5/fa365093912cfb4047b393f6ad8065f59798c470
npm ERR! addLocal Could not install /var/folders/c2/33k9s6bs35d4p8gldgnl0gxc0000gn/T/npm-43780-79905adc/git-cache-18753e5f/fa365093912cfb4047b393f6ad8065f59798c470
npm ERR! addLocal Could not install /var/folders/c2/33k9s6bs35d4p8gldgnl0gxc0000gn/T/npm-43780-79905adc/git-cache-992a369e/fa365093912cfb4047b393f6ad8065f59798c470
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node4-lts/4.4.7/bin/node" "/usr/local/bin/npm" "install" "github:rethinkdb/horizon#next"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/giro/stardust-rethink-server/npm-debug.log

I can't do "npm install @horizon/server" because then I have no CLI.

Please advise.

**Comment by deontologician** [comment]
This is a problem installing from github, since we don't have a package.json at the root of our project. We have a monorepo, and installing from github directly from a subdirectory isn't [supported by npm](https://github.com/npm/npm/issues/2974#issuecomment-169451651). You'll want to pull down the github repo and build it yourself, possibly using the `test/setupDev.sh` script

**Comment by GeoffreyPlitt** [comment]
Thanks.

Note: I got past this using https://github.com/shama/napa and the following "scripts" entry:

`"postinstall": "napa rethinkdb/horizon#next"`
