### ISSUE TITLE
Entities with NULL ids

### ISSUE THREAD

**Issue by intellix** [rethinkdb/horizon#670]
So I've got a TS class like: 

``` js
export interface IThing {
  id: number;
  name: string;
}

export class Thing implements IThing {
  constructor(
    public id,
    public name: string
  ) {}
}
```

When I want to store it in Horizon, I do something like: 

``` js
let t = new Thing(null, 'Something');
this.myService.things.store(t);
```

but nothing happens, not even an error (I'm sure I had one before though). I either have to give it an ID of undefined or do `delete t.id;` before trying to store it.

Not 100%, but maybe it should be allowed to pass in a NULL id field and treat it as being undefined/missing?

**Comment by deontologician** [comment]
Hi @intellix,

This looks like a bug to me, we should probably be throwing an error. I think in TS this should be implemented as an optional field most likely. RethinkDB throws an error if you try to store something with an `id` of null, so I'm not sure what's happening. @Tryneus do you know what the server does when it gets a null id?

**Comment by deontologician** [comment]
Yeah, I think this just needs to ensure that the id is undefined, rather than being set to null.
