### ISSUE TITLE
New index specification format for `hz schema`

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/horizon#706]
Currently a schema `.toml` file contains index specifications as strings. We decided to start using a structured index specification in Horizon 2.0, to make these easier and more explicit to write and read.

@Tryneus can you post some details on the new format please for reference once you have a full spec?

**Comment by Tryneus** [comment]
The format should look like this, for an example collection 'foo' with two indexes, one on the nested field 'a.b' and regular field 'c', and the other on the fields 'bar' and 'baz':

```
[collections.foo]
[[collections.foo.indexes]]
fields = [['a','b'],['c']]
[[collections.foo.indexes]]
fields = [['bar'],['baz']]
```

Working on a PR now.
