### ISSUE TITLE
make-token should not connect to rethinkdb

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/horizon#718]
Right now make-token checks that the user exists before creating the token. While this might prevent simple mistakes, anyone getting a token for a user that doesn't exist will get an error when they connect. It complicates the make-token command and doesn't provide much benefit (now you need to specify all rethinkdb connection options and you have to worry about a rethinkdb database that's already running which may have random ports... etc etc)

**Comment by Tryneus** [comment]
Fixed by #729.
