### ISSUE TITLE
Express server example with own website content

### ISSUE THREAD

**Issue by BenjaminFaal** [rethinkdb/horizon#724]
Server version: 1.1.3
Client version: 1.1.3

Node/Express server code:
`'use strict';

const PORT = 80;

const express = require('express');
const path = require('path');
const horizon = require('@horizon/server');

const app = express();
app.use(express.static(path.join(__dirname, '../dist')));

const http_server = app.listen(PORT);

var options = {auth: {token_secret: 'my_super_secret_secret'}};
const horizon_server = horizon(http_server, options);

console.log('Listening on port', PORT, 'Horizon', PORT );`

My problem is that once i try to add a static mapping for my website it just wont connect and throws this error:

`polling-xhr.js:250 GET http://192.168.1.194/horizon/?EIO=3&transport=polling&t=LPLSRTG 400 (Bad Request)`

**Comment by deontologician** [comment]
This is very likely fixed in 2.0. We got rid of engine.io

**Comment by BenjaminFaal** [comment]
Hello, any idea when 2.0 will be released? Or how i can use it already because i can see the code is already there.

**Comment by zalmoxisus** [comment]
@deontologician, maybe publishing `2.0.0-alpha-1` to npm?

**Comment by deontologician** [comment]
Beta will be out today come hell or high water!

**Comment by BenjaminFaal** [comment]
NICE! cant wait haha, will test immediately and report back!

**Comment by BenjaminFaal** [comment]
I see version 2.0.0 beta 3 now but it's not yet on npmjs?

**Comment by deontologician** [comment]
it is on npm, just install horizon@beta

**Comment by BenjaminFaal** [comment]
Hey i got it to work kind of, i just have this error now:

`error: Connection to RethinkDB terminated: Error: The database horizon does not exist.  Run`hz schema apply`to initialize the database, then start the Horizon server.`

When i run hz schema apply it does not work and just prints all the required arguments but i dont know what to fill in to be honest.

**Comment by danielmewes** [comment]
@BenjaminFaal It expects a schema file name. Check http://horizon.io/docs/permissions/ for how to write a schema file.
If you instantiate the server with the `auto_create_collection` and `auto_create_index` options (only use these for development + testing), you can probably just pass an empty file to `hz schema apply`, since all the collections and indexes will be created later on first access.

**Comment by deontologician** [comment]
So a couple questions:
1. Are you migrating an app from 1.0, or making a new 2.0 app?
2. are you embedding or using `hz serve`?

**Comment by BenjaminFaal** [comment]
@danielmewes Thanks i think i get it now!

@deontologician its a new 2.0 app and im embedding with the express server example

**Comment by BenjaminFaal** [comment]
Thanks everyone, 2.0.0-beta-3 seems to fix the issue with websockets this issue can be closed now!
