### ISSUE TITLE
Documentation: client constructor hostname and port

### ISSUE THREAD

**Issue by ejsuncy** [rethinkdb/horizon#725]
The client `Horizon` model has a constructor that takes an object of option keys and values, one of which is `host`. It is not apparent from the [docs here](http://horizon.io/api/horizon/#constructor) that the `host` option is a string that includes the port number if applicable. Perhaps providing an example or two there such as `'host'`:`'localhost:8181'` would be more helpful, as I had to dig in to the source to find the constructor of the `Horizon` object.

I bring this up because I'm developing my web app and using BrowserSync, which serves the static files on port 5555, for example. I'm also using horizon on 8181, and I need to override the default port that Horizon client tries to connect to (in this case, the default was port 5555).

Thanks!

**Comment by danielmewes** [comment]
Thanks for the feedback @ejsuncy . I moved your suggestion to the special documentation issue tracker: https://github.com/rethinkdb/horizon-docs/issues/107
