### ISSUE TITLE
2.0.0-beta-3 Error: Observable.timer.map.publish is not a function

### ISSUE THREAD

**Issue by LawJolla** [rethinkdb/horizon#735]
Server version: 2.0.0-beta-3
Client version: 2.0.0-beta-3

I tried a clean upgrade from 1.1.3 (no migration, deleted Rethink tables).  

I'm using Webpack Dev Server, host: 'localhost:8181' in the Horizon constructor.  

Webpack builds without error.  But the web browser instantly errors out with this stack trace..

`
bundle.js:42181 Uncaught TypeError: _Observable.Observable.timer(...).map(...).publish is not a functionHorizonSocket @ bundle.js:42181Horizon @ bundle.js:35517(anonymous function) @ bundle.js:35452__webpack_require__ @ bundle.js:556fn @ bundle.js:87(anonymous function) @ bundle.js:8189(anonymous function) @ bundle.js:8307__webpack_require__ @ bundle.js:556fn @ bundle.js:87(anonymous function) @ bundle.js:588__webpack_require__ @ bundle.js:556(anonymous function) @ bundle.js:579(anonymous function) @ bundle.js:582
bundle.js:614 [WDS] Hot Module Replacement enabled.
`

Line 42181 source maps back to...

`
_this2.keepalive = _Observable.Observable.timer(keepalive * 1000, keepalive * 1000).map(function (n) {
          return _this2._multiplex({ type: 'keepalive', n: n });
        }).publish();
`

Is this an RxJS dependency issue? I'm not smart enough to solve this riddle.

**Comment by zubair-io** [comment]
I believe this is related to #734

**Comment by LawJolla** [comment]
Would to believe that I did a search and didn't see it.  I need to level up my Github.  Thanks!

**Comment by zubair-io** [comment]
You can try adding `require('rxjs/add/operator/publish');` to line 41 of   node_modules/@horizon/client/lib/socket.js

**Comment by LawJolla** [comment]
Beat me to it, thank you.  Temp fixed worked.

**Comment by dalanmiller** [comment]
This is now fixed in beta 4 with #734
