### ISSUE TITLE
2.0.0-beta-4 webpack problem?

### ISSUE THREAD

**Issue by daniel1943** [rethinkdb/horizon#742]
Using [this boilerplate](https://github.com/ctrlplusb/react-universally) 

Keep getting:

`ReferenceError: WebSocket is not defined
    at Horizon (/home/home/dev/react-universally/node_modules/@horizon/client/src/index.js:25:19)
`

I installed from NPM, cleared cache, tried compiling from source... always the same.

**Comment by deontologician** [comment]
You'll need to polyfill WebSocket, it expects it to be a global

**Comment by deontologician** [comment]
Mentioned this issue in https://github.com/rethinkdb/horizon-docs/issues/111
