### ISSUE TITLE
client websockets keepalive doesn't appear to be working

### ISSUE THREAD

**Issue by transcranial** [rethinkdb/horizon#744]
Server version: 2.0.0-beta-4
Client version: 2.0.0-beta-4

I'm having an issue with the socket connection timing out with AWS ELB (see comment https://github.com/rethinkdb/horizon/issues/527#issuecomment-225693019). Looking at the websockets frames in chrome devtools, it doesn't look like any messages of type `keepalive` is sent.

Submitted PR #743. These changes fixes the issue for me.

**Comment by deontologician** [comment]
Fixed in #743
