### ISSUE TITLE
[2.0.0-beta-4] token verification failure

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/horizon#747]
Reported by @vramana whose setup is here => https://github.com/vramana/horizon-webpack,
while trying to follow [this yet unpublished guide](https://github.com/rethinkdb/horizon-docs/blob/horizon-2.0/permissions.md#making-an-admin-auth-token-admin) in the docs. 
You can repro this by using one of the example directories:
- `cd examples/vue-chat-app`
- `hz init`
- `hz make-token admin`
- `hz serve --dev --debug`
- In the browser attempt to use token and connect to Horizon like code example in documentation

Result: 

```
🌄 Horizon ready for connections
debug: Client connection established.
debug: Received handshake: {"request_id":0,"method":"token","token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6ImFkbWluIiwicHJvdmlkZXIiOm51bGwsImlhdCI6MTQ3MTAyODkxMSwiZXhwIjoxNDcxMTE1MzExfQ.5dUu5re32MLyl_ZmIlqh7E63hmBHmBwe5IfZf_YKGG8ysiGHx4ng5EeBd_kaudfI5AgZZFJnShNA7K9ZxDbw0g"}
debug: Closing client connection with message: JsonWebTokenError: invalid signature
debug: info: {"request_id":0,"error":"JsonWebTokenError: invalid signature","error_code":0}
debug: Client connection terminated.
```

**Comment by dalanmiller** [comment]
Also we should probably have a test for this that creates a new token and tries to connect with it if we don't already.

**Comment by bartekus** [comment]
```
var horizon = Horizon({
  host: 'localhost:8181',
  authType: {
    token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpZCI6Ijk0MjQ2ZWIzLWVhMTEtNDU3NC1hZGNjLWE2MjM3OTI0ZjJiMCIsInByb3ZpZGVyIjpudWxsLCJpYXQiOjE0NzEwMjQ4MzIsImV4cCI6MTQ3MTExMTIzMn0.z5KoxKnv4ECJ2cqJEYWOXK53LrlXGtzOX9cTNna1xrExYfyPBIpY-XnmBGOjM1fp498rLTjYe-Mrkbzgoh6RkA',
    storeLocally: false
  }
});
```

The current configuration checks for the token right away but I'd reckon that this would do:

```
var horizon = Horizon({
  host: 'localhost:8181',
  authType: 'unauthenticated',
});
```

Reason for it is that we are working with client side and as a new user arriving at the service, you would not have a token to begin with but still would want to be able to access the site.

**Comment by vramana** [comment]
@Bartekus I don't understand what you are saying correctly but the problem here is not that. #748 is the correct fix. A command line default was overriding the token-secret from `secrets.toml` and that is causing the issue.

**Comment by bartekus** [comment]
@vramana I'm sorry, I didn't understand the underlining problem correctly so obviously my answer is incorrect in that respect. That being said, thank you for providing the context for me to grok the issue at hand.
