### ISSUE TITLE
We should give a better error if you run `hz serve` without a PEM file.

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/horizon#761]
Currently we produce this output:

```
serve failed with Error: Could not access file "./horizon-key.pem" for running HTTPS server: Error: ENOENT: no such file or directory, open '/home/mlucy/hzdemo/horizon-key.pem'
```

It would be nice if we gave an error that:
- Explains more clearly what went wrong if you don't know what a PEM file is.
- Recommends running with `--dev` during development.
- Possibly tells you how generate a self-signed cert for testing?
- Possibly links to a page explaining what certificates are and how to generate a self-signed one for testing?

**Comment by deontologician** [comment]
we have a make-cert command too we could recommend

**Comment by danielmewes** [comment]
This is probably important because it's literally the first thing (I think) one gets when running `hz serve` without further configuration.
