### ISSUE TITLE
Bad error message when trying to use `hz schema save`

### ISSUE THREAD

**Issue by mlucy** [rethinkdb/horizon#762]
After `hz serve`, I tried to run `hz schema save` in the same directory, and I got this error:

```
error: rethinkdb stderr: Directory 'rethinkdb_data' is already in use, perhaps another instance of rethinkdb is using it.
RethinkDB process terminated with error code 1.                                                                          
```

What I needed to do was pass `-c localhost:<port horizon printed on startup>`, but the error message didn't do a good job of leading me toward that.

We should probably also consider dumping the currently running host/port into a file or something when `hz serve` starts so that commands like `hz schema save` can just work.

**Comment by Tryneus** [comment]
This looks like a duplicate of #720.

**Comment by mlucy** [comment]
Closing as a duplicate.
