### ISSUE TITLE
hz migrate is broken "procPromise is not a function" 

### ISSUE THREAD

**Issue by dalanmiller** [rethinkdb/horizon#779]
On horizon@2.0.0-beta-7 so maybe this was already caught.

Way to repro:
1. Install horizon@1.1.3
2. Go to /examples/vue-chat-app
3. Remove `rethinkdb_data` if it's there
4. hz serve --dev && type random gibberish into app to create collections and indexes
5. Shutdown horizon app
6. npm install -g horizon@2.0.0-beta-7
7. Then attempt `hz migrate`

```
$ hz migrate
Setup
 ├── Connecting to RethinkDB
 └── Successfully connected
Validating current schema version
 └── Pre-2.0 schema found
Backing up rethinkdb_data directory
Cleaning up...
 ├── Closing rethinkdb connection
procPromise is not a function
```

**Comment by deontologician** [comment]
Fixed in #776
