### ISSUE TITLE
Can't move config.toml

### ISSUE THREAD

**Issue by tvld** [rethinkdb/horizon#781]
I've tried to move config.toml from .hz to project folder, but it does not work even though `--config config.toml`  seems correct...?
Using the dockerfile.yml

**Comment by deontologician** [comment]
Just an update, we closed this since we removed the --config option altogether. There are now several configuration files, and it's better to just have it look in the default location, rather than adding a new flag for each config file.

**Comment by tvld** [comment]
thanks for the update...  ))
