### ISSUE TITLE
Link to server docs is 404

### ISSUE THREAD

**Issue by ivan-kleshnin** [rethinkdb/horizon#782]
From http://horizon.io/docs/getting-started/:

> You can find the complete list of command line flags for hz serve in the documentation for the Horizon server.

Links to
http://horizon.io/docs/server

Which is 404

**Comment by dalanmiller** [comment]
Fixed with rethinkdb/horizon-docs@4895a5f56fd4cf06c7bced1a84ae7157903c52a7

Thank you @ivan-kleshnin 🎯
