### ISSUE TITLE
Google validation of id_token fails

### ISSUE THREAD

**Issue by lirbank** [rethinkdb/horizon#793]
Server version: 2.0.0
Client version: 2.0.0
1. Sign in with horizon
2. Copy token from address bar or local storage
3. Add token to https://www.googleapis.com/oauth2/v3/tokeninfo?id_token=XYZ123

Response:

``` json
{
 "error_description": "Invalid Value"
}
```

Info: https://developers.google.com/identity/protocols/OpenIDConnect#validatinganidtoken

**Comment by Tryneus** [comment]
The token in the address bar or local storage is a horizon JWT, not the token from the Google servers.  The Google token is used internally to check the user's Google account ID and correspond it to a horizon user row; it is never sent to the browser.

**Comment by lirbank** [comment]
Oh, that explains it!
