### ISSUE TITLE
horizon._reql_conn.connection is not defined

### ISSUE THREAD

**Issue by lirbank** [rethinkdb/horizon#807]
Server version: 2.0.0
Client version: 2.0.0

See "Accessing the Rethinkdb r object" at http://horizon.io/docs/embed/

`horizon._reql_conn` is not defined, so `const conn = horizon._reql_conn.connection();` fails with `TypeError: Cannot read property 'connection' of undefined`

**Comment by deontologician** [comment]
ping @Tryneus 

As an aside, it was a bad idea on our part to put an underscore prefixed variable into the official docs

**Comment by Tryneus** [comment]
`_reql_conn` is defined on the server object, not the module (as you could be running multiple horizon servers with different rethinkdb instances backing them), this is incorrect in the docs.

**Comment by deontologician** [comment]
Closing since this was basically a docs issue.
