### ISSUE TITLE
Does it work on windows?

### ISSUE THREAD

**Issue by eprozium** [rethinkdb/horizon#809]
Does it work on Windows? e.g. Win 7 and 8 ?

Thank you.

**Comment by danielmewes** [comment]
@eprozium We've only tested the Horizon server on Windows 10, but there it works. You just need to get a recent version of node.js (4.4.0 or higher) and then install Horizon through `npm install -f horizon`.

The `hz serve` tool will look for a `rethinkdb.exe` binary in the current directory, so you'll have to download RethinkDB from https://rethinkdb.com/docs/install/windows/ and place the `rethinkdb.exe` file into the directory from which you're planning to use the `hz` utility (alternatively you can start the RethinkDB server manually and point `hz` to it. See the corresponding options in `hz serve --help`).

**Comment by eprozium** [comment]
> We've only tested the Horizon server on Windows 10, but there it works. 

So I guess it's also only 64 bit than :) .

**Comment by danielmewes** [comment]
@eprozium We currently only provide RethinkDB binaries for 64-bit Windows. You can compile RethinkDB from source for 32 bit Windows, but it would be quite a bit of setup work (you'll need a recent version of Visual C++ and Cygwin among others, see https://github.com/rethinkdb/rethinkdb/blob/next/WINDOWS.md ).

**Comment by eprozium** [comment]
@dalanmiller Thank you for the information.
