### ISSUE TITLE
Moving to horizon 2.0.0 and express

### ISSUE THREAD

**Issue by alexarsh** [rethinkdb/horizon#810]
Hi,

I moved to 2.0.0 and embedded my horizon app inside express and it totally broke my app.
[The errors I see in client](http://slexy.org/view/s2WOIPe8jJ)
In addition, my google login redirect me to:
https://my_site.com/https://my_site.com/horizon/google#/?_k=cuwus9
And my facebook login just fail and brings me to an empty page.

On the server, the only suspicious thing is when I run: 
hz serve --debug --serve-static ./dist --start-rethinkdb --bind all
I see the following error
error: rethinkdb stderr: warn: Cache size does not leave much memory for server and query overhead (available memory: 812 MB)

although I already fixed that before upgrading to 2.0.0 following [this thread](https://discuss.horizon.io/t/how-much-memory-rethinkdb-need/349/6).

I use nginx reverse proxy and tried to configure it both with and without upstream ssl on the horizon side.
I'm not sure, but maybe it's related to ticket #639 

[server.js](http://slexy.org/view/s216vmnxRb)
[hz command output](http://slexy.org/view/s217zjmnea)
[npm install command output](http://slexy.org/view/s2ljvvEqXu)
[nginx config](http://slexy.org/view/s21o7nJGcO)

Server version: 2.0.0
Client version: 2.0.0

**Comment by deontologician** [comment]
It looks like this is nginx related, sending an http response code for `/horizon` instead of the websocket upgrade.

For reference, there's more discussion on this issue on the forums:
https://discuss.horizon.io/t/moving-to-horizon-2-0-0-and-express/509/12

**Comment by deontologician** [comment]
Going to close since it looks like this was sorted out
