### ISSUE TITLE
Feature request: server_time function

### ISSUE THREAD

**Issue by timothyclemansinsea** [rethinkdb/horizon#813]
My experience with SageMathCloud has taught me that it is important to use server time not one's client time because people's clients are out of sync.

**Comment by danielmewes** [comment]
Thanks for the feature request @timothyclemansinsea . There has been some previous discussion on this in https://github.com/rethinkdb/horizon/issues/194 , and to a smaller degree in https://github.com/rethinkdb/horizon/issues/50 .

I'm going to close this as a duplicate.
