### ISSUE TITLE
"clearAuthTokens" not found instantiated on Horizon client

### ISSUE THREAD

**Issue by yankeeinlondon** [rethinkdb/horizon#816]
Server version: 2.0.0
Client version: 2.0.0

I'm noticing that when I try to logout/un-authenticate a user using the documented `clearAuthTokens` I get an error. You can see the error from the Chrome debugger below along with some debugging I did directly afterward with a breakpoint set right before the error.

![2016-09-09_13-17-55](https://cloud.githubusercontent.com/assets/980757/18386711/8d1dc50a-7690-11e6-8157-4fdaea89065e.png)

further with Chrome object introspection you can what properties are defined on the object:

![2016-09-09_13-12-59](https://cloud.githubusercontent.com/assets/980757/18386724/9f85df84-7690-11e6-8b3b-927c5f90a61d.png)

**Comment by yankeeinlondon** [comment]
As a temporary work-around I'm just removing the JWT token from localStorage directly but clearly this is quite "hacky".

**Comment by albertjan** [comment]
Shouldn't you be calling the static function `Horizon.clearAuthTokens()`? 

http://horizon.io/api/horizon/#clearauthtokens

**Comment by yankeeinlondon** [comment]
ahhh. yes that's it. I need more sleep. closing.
