### ISSUE TITLE
RethinkDB is shutting down (company behind horizon)

### ISSUE THREAD

**Issue by arthurvi** [rethinkdb/horizon#850]
Sad news today :( 
https://rethinkdb.com/blog/rethinkdb-shutdown/

Horizon and RethinkDB are both beautiful projects and have lots of potential. We should workout a way to keep the horizon train going. Will there be any update from the team about the current progress? The most notable active projects are Plugins and React Native support right? Any more on this list and the current status?

Thanks!

**Comment by yankeeinlondon** [comment]
Is there anything the community can do to help out an effort to move this forward without the helpful umbrella of the Rethinkdb company? Will be PR's be brought into the product time effectively? Also wondering, were any conversations with Microsoft had about them contributing $$$? It just feels like they're in a aligned position to get behind this kind of a stack. Their DB story is quite antiquated in irrelevant to the startup community. Anyway, I do hope to see both Horizon and Rethink to move forward somehow.

**Comment by marshall007** [comment]
@ksnyde we're definitely looking for active community members who are interested in contributing to the project going forward. Join us on [#open-rethinkdb](https://rethinkdb.slack.com/archives/open-rethinkdb) in Slack and let us know if and how you'd be willing to help out in the [Google form](https://goo.gl/forms/tFjI4JI4AvIcPi3D3).

**Comment by tvld** [comment]
I think the community is [picking up nicely](https://docs.google.com/document/d/1f8qODp7voKIqwioQ3si69q3-ruc7h3ncfH0KoHYv_4k/edit)

**Comment by jumasheff** [comment]
Good news:

"...Cloud Native Computing Foundation (CNCF) purchased the rights to the RethinkDB source code and contributed it to The Linux Foundation under the permissive ASLv2 license..."
https://rethinkdb.com/blog/rethinkdb-joins-linux-foundation/

I think this issue can be closed now.

**Comment by rnenjoy** [comment]
Pretty awesome news!

**Comment by lgleim** [comment]
@marshall007 Can you provide some insight into the status of the transitioning efforts? I am currently right at the edge of hard forking to our companies' private repositories... I do think it is despicable not to recontribute but I am not going to spend hundreds of hours maintaining compatibility with an unmaintained project without any plan forward either.

**Comment by riyadhzen** [comment]
@lgleim Can you give some insights on the things that you worked on in your fork, as this can really be helpful to show how people are working with horizon and the difficulties that they are facing.

**Comment by marshall007** [comment]
@lgleim @riyadhzen see https://github.com/rethinkdb/horizon/issues/872#issuecomment-286613366. I'm gonna close this issue in favor of that one just so we can consolidate the discussion.
