### ISSUE TITLE
[website] horizon.io taken by blockchain gaming company

### ISSUE THREAD

**Issue by ghost** [rethinkdb/horizon#898]
Remove references to `horizon.io` as the domain is taken by blockchain gaming company.
The issue template references the URL as well as the project's URL.

The Horizon Twitter account seems dead but links to `horizon.io` as well.

If this project is dead maybe remove the URL referneces and archive this repository.

```
<!--
If you have a question,  please open a new topic in Horizon's Help forum:
    https://discuss.horizon.io/c/get-help

If you're reporting a bug please include the following:
-->
```

**Comment by JosXa** [comment]
Must have been the 5th time or so I stumbled over it, every time getting extremely confused and closing the tabs again after getting excited initially. "Ethereum blockchain, a Game? That's your end goal? Man, you sounded so professional in all those youtube talks but now you're doing *that*?" 😆 

Please just drop that URL, it ain't that hard

**Comment by srh** [comment]
LOL.  Thanks for making this comment @JosXa , and @fibric for the report, I must have clicked through this Github notification last time.  I'll scrub out the URLs when I get the chance (which should be today).

**Comment by srh** [comment]
I made two PR's.  One of them changes the documentation links to point at http://samuelhughes.com/rethinkdb/horizon-docs/docs/index.html , and if anybody has a better place they'd like to host the docs, we could point it there instead.

**Comment by abserari** [comment]
More about it, the website link should be changed, too
![image](https://user-images.githubusercontent.com/32089134/105275103-8443d180-5bd9-11eb-9f68-99a83ddce747.png)

**Comment by srh** [comment]
I have removed that link and merged the PR's.
